# ddIRC — developer tasks.
#
# `make fix` is the one to remember: it formats and auto-fixes both halves of
# the project, then re-checks the result so a fix that breaks something is
# caught in the same command. Everything else here is a piece of that.
#
# Tool paths are auto-detected but overridable, because Flutter is often not on
# PATH on Windows:
#
#     make fix FLUTTER=/c/src/flutter/bin/flutter

FLUTTER ?= $(shell command -v flutter 2>/dev/null || echo "$$HOME/flutter/bin/flutter")
DART    ?= $(shell command -v dart    2>/dev/null || echo "$$HOME/flutter/bin/dart")
CARGO   ?= cargo

# The native core is a Cargo workspace of its own, one level down.
RUST     := irc-core
MANIFEST := --manifest-path $(RUST)/Cargo.toml

# Dart sources. `lib/src/rust/` is generated by flutter_rust_bridge_codegen and
# is already format-clean, so passing the whole tree costs nothing and cannot
# churn it.
DART_SRC := lib

COMPOSE ?= docker compose -f dev/compose.yaml

.DEFAULT_GOAL := help
.PHONY: help fix fmt lint test test-integration build codegen clean \
        dev-server dev-server-stop dev-server-clean dev-server-logs

help:
	@echo "ddIRC"
	@echo ""
	@echo "  make fix      format + auto-fix Dart and Rust, then lint"
	@echo "  make fmt      format only"
	@echo "  make lint     analyze Dart, clippy Rust (warnings are errors)"
	@echo "  make test     run the Dart and Rust test suites (hermetic)"
	@echo "  make test-integration  end-to-end, needs make dev-server"
	@echo "  make build    debug build for Windows"
	@echo "  make codegen  regenerate the Dart bindings from the Rust API"
	@echo "  make clean    drop build output for both halves"
	@echo ""
	@echo "  make dev-server        local IRC server on 127.0.0.1:6697 (TLS)"
	@echo "  make dev-server-stop   stop it, keeping accounts and certs"
	@echo "  make dev-server-clean  stop it and throw the state away"
	@echo "  make dev-server-logs   follow its log"
	@echo ""
	@echo "Override a tool path if it is not on PATH, e.g."
	@echo "  make fix FLUTTER=/c/src/flutter/bin/flutter"

## Format everything, apply what the linters can fix themselves, then check.
fix: fmt
	$(DART) fix --apply $(DART_SRC)
	$(CARGO) clippy $(MANIFEST) --workspace --all-targets --fix \
		--allow-dirty --allow-staged
	@$(MAKE) --no-print-directory lint

fmt:
	$(DART) format $(DART_SRC)
	$(CARGO) fmt $(MANIFEST) --all

## Check only — no file is modified. This is what CI should run.
lint:
	$(FLUTTER) analyze
	$(CARGO) fmt $(MANIFEST) --all -- --check
	$(CARGO) clippy $(MANIFEST) --workspace --all-targets -- -D warnings

## Everything that needs no network and no Docker.
test:
	$(FLUTTER) test
	$(CARGO) test $(MANIFEST) --workspace

## End-to-end against the local server; `make dev-server` must be up.
#
# These are `#[ignore]`d so the line above stays hermetic — it runs in CI and on
# machines with no Docker.
test-integration:
	$(CARGO) test $(MANIFEST) -p ddirc-core --test dev_server -- --ignored

build:
	$(FLUTTER) build windows --debug

# Needs `flutter` on PATH: the generator shells out to it by name.
codegen:
	PATH="$(dir $(FLUTTER)):$$PATH" flutter_rust_bridge_codegen generate

clean:
	$(FLUTTER) clean
	$(CARGO) clean $(MANIFEST)

## A real IRC server to test against, on loopback only.
#
# The client is TLS-only and verifies certificates, so this serves real TLS with
# a self-signed certificate rather than plaintext on 6667. `--wait` blocks until
# the TLS port actually accepts, so a test can run straight after this returns.
dev-server:
	$(COMPOSE) up -d --wait
	@echo ""
	@echo "  irc://localhost:6697 (TLS)"
	@echo "  certificate: dev/ergo/fullchain.pem (trust it; do not disable verification)"

dev-server-stop:
	$(COMPOSE) down

## Also drops the accounts, certificates and generated config in dev/ergo/.
dev-server-clean:
	$(COMPOSE) down -v
	rm -rf dev/ergo

dev-server-logs:
	$(COMPOSE) logs -f
