# ddIRC — developer tasks.
#
# `make fix` is the one to remember: it formats and auto-fixes both halves of
# the project, then re-checks the result so a fix that breaks something is
# caught in the same command. Everything else here is a piece of that.
#
# Tool paths are auto-detected but overridable, because Flutter is often not on
# PATH on Windows:
#
#     make fix FLUTTER=/c/src/flutter/bin/flutter

# Windows: make sure the recipes do not run under WSL.
#
# Run from PowerShell or cmd, GNU Make resolves its default `/bin/bash` through
# PATH, and on a machine with WSL installed the first match is
# `C:\Windows\System32\bash.exe` — which is a different operating system. It
# cannot see `C:/Users/...`, has neither Flutter nor cargo on its PATH, and
# fails the first recipe with `No such file or directory` naming a path that is
# plainly there. That is the error, and nothing about it points at the cause.
#
# So Git Bash is pinned when it can be found. The 8.3 names are deliberate:
# `$(wildcard)` splits its argument on spaces whatever the escaping, so
# `C:/Program Files/...` cannot be probed, while `C:/PROGRA~1/...` can.
#
# Found nothing? Nothing is changed, and Make keeps its own default — which is
# correct on Linux and macOS, and on Windows leaves the behaviour exactly as it
# was. Override it directly if Git lives somewhere unusual:
#
#     make fix SHELL=/path/to/bash
ifeq ($(OS),Windows_NT)
  GIT_BASH := $(firstword $(wildcard \
      C:/PROGRA~1/Git/bin/bash.exe \
      C:/PROGRA~2/Git/bin/bash.exe \
      $(subst \,/,$(USERPROFILE))/scoop/apps/git/current/bin/bash.exe))
  ifneq ($(GIT_BASH),)
    SHELL := $(GIT_BASH)
    .SHELLFLAGS := -c
  endif
endif

FLUTTER ?= $(shell command -v flutter 2>/dev/null || echo "$$HOME/flutter/bin/flutter")
DART    ?= $(shell command -v dart    2>/dev/null || echo "$$HOME/flutter/bin/dart")
CARGO   ?= cargo

# Inno Setup's compiler, for `make installer`. Not part of any other target and
# not needed to build or run the app; only to package it. Unlike Flutter above
# there is no sensible fallback path to guess at, so an empty value here is what
# the target checks for and explains.
# Kept to one line each, and free of backslashes: this Make strips a backslash
# out of a $(shell) body before the shell ever sees it, so `sed 's/x\(y\)/.../'`
# silently becomes a different expression and the variable comes out empty.
ISCC    ?= $(shell command -v iscc 2>/dev/null || ls "/c/Program Files (x86)/Inno Setup 6/ISCC.exe" 2>/dev/null || ls "/c/Program Files/Inno Setup 6/ISCC.exe" 2>/dev/null)

# `1.0.0+1` in pubspec.yaml is one version for Dart and two for everyone else:
# the part before `+` is what Windows shows and compares, and the build number
# after it means nothing there. Take the first part only.
APP_VERSION := $(shell grep '^version:' pubspec.yaml | sed 's/^version:[[:space:]]*//; s/+.*//')

# The native core is a Cargo workspace of its own, one level down.
RUST     := irc-core
MANIFEST := --manifest-path $(RUST)/Cargo.toml

# Dart sources. `lib/src/rust/` is generated by flutter_rust_bridge_codegen and
# is already format-clean, so passing the whole tree costs nothing and cannot
# churn it. `test/` and `tool/` are here because they are source too: leaving
# them out is how a formatting drift gets committed and then shows up as churn
# in whichever change happens to touch the file next.
DART_SRC := lib test tool

COMPOSE ?= docker compose -f dev/compose.yaml
# The optional services - the SOCKS5 proxy and Tor - sit behind compose
# profiles so they do not start with the server. Stopping has to name them
# explicitly, because `docker compose down` on its own walks straight past a
# profiled container and leaves it running.
PROFILES ?= --profile proxy --profile tor

.DEFAULT_GOAL := help
.PHONY: help fix fmt lint test test-integration build build-release installer check-iscc \
        build-linux build-macos build-ios codegen icons clean \
        dev-server dev-server-stop dev-server-clean dev-server-logs \
        dev-proxy dev-tor dev-tor-logs dev-onion-cert

help:
	@echo "ddIRC"
	@echo ""
	@echo "  make fix      format + auto-fix Dart and Rust, then lint"
	@echo "  make fmt      format only"
	@echo "  make lint     analyze Dart, clippy Rust (warnings are errors)"
	@echo "  make test     run the Dart and Rust test suites (hermetic)"
	@echo "  make test-integration  end-to-end, needs make dev-server"
	@echo "  make build    debug build for Windows"
	@echo "  make build-release     release build for Windows"
	@echo "  make installer         wrap it in a per-user .exe (needs Inno Setup)"
	@echo "  make build-linux|build-macos|build-ios   the other hosts"
	@echo "  make codegen  regenerate the Dart bindings from the Rust API"
	@echo "  make icons    redraw the app icons from lib/src/ui/mark_spec.dart"
	@echo "  make clean    drop build output for both halves"
	@echo ""
	@echo "  make dev-server        local IRC server on 127.0.0.1:6697 (TLS)"
	@echo "                         writes dev/server.txt: where it is, how to reach it"
	@echo "  make dev-server-stop   stop it, keeping accounts and certs"
	@echo "  make dev-server-clean  stop it and throw the state away"
	@echo "  make dev-server-logs   follow its log"
	@echo "  make dev-proxy         SOCKS5 on 127.0.0.1:1080, in front of it"
	@echo "  make dev-tor           real Tor on 127.0.0.1:9050, for public nets"
	@echo "  make dev-tor-logs      follow Tor's bootstrap"
	@echo "  make dev-onion-cert    reissue the server cert for its onion name"
	@echo ""
	@echo "Override a tool path if it is not on PATH, e.g."
	@echo "  make fix FLUTTER=/c/src/flutter/bin/flutter"

## Format everything, apply what the linters can fix themselves, then check.
#
# `dart fix` is looped over the sources one at a time because it takes exactly
# one path — unlike `dart format` on the line above, which takes the list — and
# answers the whole list with a usage error rather than doing anything.
fix: fmt
	@for dir in $(DART_SRC); do $(DART) fix --apply "$$dir"; done
	$(CARGO) clippy $(MANIFEST) --workspace --all-targets --fix \
		--allow-dirty --allow-staged
	@$(MAKE) --no-print-directory lint

fmt:
	$(DART) format $(DART_SRC)
	$(CARGO) fmt $(MANIFEST) --all

## Check only — no file is modified. This is what CI should run.
#
# The Dart format check is not redundant with `analyze`, which says nothing
# about formatting at all. Without it the Dart half has no formatting gate, and
# the drift surfaces later as `make fix` rewriting files nobody edited.
lint:
	$(FLUTTER) analyze
	$(DART) format --output=none --set-exit-if-changed $(DART_SRC)
	$(CARGO) fmt $(MANIFEST) --all -- --check
	$(CARGO) clippy $(MANIFEST) --workspace --all-targets -- -D warnings

## Everything that needs no network and no Docker.
test:
	$(FLUTTER) test
	$(CARGO) test $(MANIFEST) --workspace

## End-to-end against the local server; `make dev-server` must be up.
#
# These are `#[ignore]`d so the line above stays hermetic — it runs in CI and on
# machines with no Docker.
test-integration:
	$(CARGO) test $(MANIFEST) -p ddirc-core --test dev_server -- --ignored

build:
	$(FLUTTER) build windows --debug

## The other desktops and iOS. Each has to run on that host - there is no
## cross-compiling a Flutter runner - and none of them has been built yet.
## See the README: they are scaffolded and configured, not proven.
build-linux:
	$(FLUTTER) build linux --debug

build-macos:
	$(FLUTTER) build macos --debug

build-ios:
	$(FLUTTER) build ios --debug --no-codesign

## A Windows release build, and an installer around it.
#
# `make build` above is the debug build, which is what you want while working.
# This is the one that gets shipped, and `installer` depends on it because an
# installer wrapping a debug build is a mistake that only shows up in the hands
# of whoever downloaded it.
build-release:
	$(FLUTTER) build windows --release

## Package the release build as a per-user .exe installer.
#
# Needs Inno Setup 6.3+, which is a dependency of nothing else here - override
# ISCC if it lives somewhere unusual. Output lands in build/installer/.
#
# The check for it is a prerequisite rather than the first line of the recipe,
# so a missing Inno Setup is reported now instead of after a release build has
# finished and there is nothing left to do with it.
installer: check-iscc build-release
	"$(ISCC)" /DAppVersion=$(APP_VERSION) windows/installer/ddirc.iss
	@echo "-> build/installer/ddIRC-$(APP_VERSION)-windows-x64-setup.exe"

check-iscc:
	@if [ -z "$(ISCC)" ]; then \
	    echo "ISCC.exe not found. Install Inno Setup 6.3+ (https://jrsoftware.org/isdl.php),"; \
	    echo "or point at it: make installer ISCC=/path/to/ISCC.exe"; \
	    exit 1; \
	fi

# Needs `flutter` on PATH: the generator shells out to it by name.
codegen:
	PATH="$(dir $(FLUTTER)):$$PATH" flutter_rust_bridge_codegen generate

## Redraw every launcher icon from the mark's spec.
#
# The output is committed, so this only needs running after MarkSpec
# changes - and `flutter test` fails if it was needed and not run.
icons:
	$(DART) run tool/make_icons.dart

clean:
	$(FLUTTER) clean
	$(CARGO) clean $(MANIFEST)

## A real IRC server to test against, on loopback only.
#
# The client is TLS-only and verifies certificates, so this serves real TLS with
# a self-signed certificate rather than plaintext on 6667. `--wait` blocks until
# the TLS port actually accepts, so a test can run straight after this returns.
# The address and the certificate's fingerprint go into dev/server.txt rather
# than scrolling past once: ergo generates the certificate per checkout, so
# none of it is the same on two machines. Stopping deletes the file again,
# because a stale one describing a server that is not up would be worse than
# having none.
dev-server:
	$(COMPOSE) up -d --wait
	@sh dev/server-info.sh
	@echo ""
	@cat dev/server.txt

# Every profile, not just the default one: a plain `down` leaves the proxy and
# Tor containers running, and a Tor daemon nobody remembers starting is exactly
# the kind of thing that should not outlive the server it was brought up for.
dev-server-stop:
	$(COMPOSE) $(PROFILES) down
	@rm -f dev/server.txt

## Also drops the accounts, certificates and generated config in dev/ergo/.
dev-server-clean:
	$(COMPOSE) $(PROFILES) down -v
	rm -rf dev/ergo dev/server.txt

## A SOCKS5 proxy in front of the dev server, for testing the proxy setting.
#
# Shares the server's network namespace, so the client asks it for the same
# 127.0.0.1:6697 it would otherwise dial and the certificate still verifies.
# Offline and deterministic; this is the one to test against.
dev-proxy: dev-server
	$(COMPOSE) --profile proxy up -d socks5
	@# Not `--wait`: the proxy shares the server's network namespace, so it
	@# cannot carry a health check of its own and compose calls it healthy the
	@# moment it starts - including when it exits immediately, which is what a
	@# misconfigured one does. Probe the port from inside that shared namespace
	@# instead, so a dead proxy fails here rather than as a puzzling client
	@# error five minutes later.
	@sleep 1
	@$(COMPOSE) exec -T ircd nc -z 127.0.0.1 1080 \
	  || (echo "socks5 is not listening; try: $(COMPOSE) logs socks5" && exit 1)
	@echo ""
	@echo "SOCKS5 on 127.0.0.1:1080, in front of 127.0.0.1:6697."
	@echo "Try:  ddirc-cli --server 127.0.0.1 --port 6697 \\"
	@echo "        --proxy 127.0.0.1:1080 --nick test"

## Real Tor: a SOCKS port for public networks, and an onion for the local one.
#
# Tor will not route to a private address, so the dev server is reached the
# other way round - published as an onion service. A cold start bootstraps for
# a minute or so; `make dev-tor-logs` to watch it.
dev-tor: dev-server
	@# --build because the torrc is baked into the image: without it an edit
	@# to dev/tor/ is silently ignored and the container runs the old config.
	$(COMPOSE) --profile tor up -d --build --wait tor
	@echo ""
	@echo "Tor SOCKS5 on 127.0.0.1:9050."
	@echo "Public networks go through the SOCKS port."
	@echo "The dev server is also reachable at, over that same port:"
	@echo ""
	@# Tor writes the address a moment after it reports healthy, so this
	@# waits rather than reporting a file that is about to exist.
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
	  addr=$$($(COMPOSE) exec -T tor cat /var/lib/tor/ircd/hostname \
	          2>/dev/null | tr -d '\r\n'); \
	  if [ -n "$$addr" ]; then echo "  $$addr"; break; fi; \
	  sleep 1; \
	done
	@echo ""
	@echo "Its certificate will not cover that name until you run:"
	@echo "  make dev-onion-cert"

dev-tor-logs:
	$(COMPOSE) --profile tor logs -f tor

## Reissue the dev server's certificate so it covers its onion address.
#
# Needed because the address comes from a key Tor generates on first start, so
# it cannot be known when the certificate is made. Without it every connection
# over Tor fails on the name - correctly, since onion addresses are verified
# like any other host.
dev-onion-cert:
	@sh dev/onion-cert.sh

dev-server-logs:
	$(COMPOSE) logs -f
