// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/tor.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<IrcEvent> dco_decode_StreamSink_irc_event_Sse(dynamic raw);

  @protected
  RustStreamSink<TorStatus> dco_decode_StreamSink_tor_status_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthOutcome dco_decode_auth_outcome(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AuthOutcome dco_decode_box_autoadd_auth_outcome(dynamic raw);

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw);

  @protected
  ConnectionStatus dco_decode_box_autoadd_connection_status(dynamic raw);

  @protected
  ProxyConfig dco_decode_box_autoadd_proxy_config(dynamic raw);

  @protected
  ServerConfig dco_decode_box_autoadd_server_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  CleanOutcome dco_decode_clean_outcome(dynamic raw);

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  IrcEvent dco_decode_irc_event(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MemberView> dco_decode_list_member_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RemovedItem> dco_decode_list_removed_item(dynamic raw);

  @protected
  List<TextSpan> dco_decode_list_text_span(dynamic raw);

  @protected
  MemberView dco_decode_member_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ProxyConfig? dco_decode_opt_box_autoadd_proxy_config(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  ProxyConfig dco_decode_proxy_config(dynamic raw);

  @protected
  RemovedItem dco_decode_removed_item(dynamic raw);

  @protected
  ServerConfig dco_decode_server_config(dynamic raw);

  @protected
  SpanStyle dco_decode_span_style(dynamic raw);

  @protected
  Target dco_decode_target(dynamic raw);

  @protected
  TextSpan dco_decode_text_span(dynamic raw);

  @protected
  TorStatus dco_decode_tor_status(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<IrcEvent> sse_decode_StreamSink_irc_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TorStatus> sse_decode_StreamSink_tor_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthOutcome sse_decode_auth_outcome(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AuthOutcome sse_decode_box_autoadd_auth_outcome(SseDeserializer deserializer);

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(SseDeserializer deserializer);

  @protected
  ConnectionStatus sse_decode_box_autoadd_connection_status(
    SseDeserializer deserializer,
  );

  @protected
  ProxyConfig sse_decode_box_autoadd_proxy_config(SseDeserializer deserializer);

  @protected
  ServerConfig sse_decode_box_autoadd_server_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  CleanOutcome sse_decode_clean_outcome(SseDeserializer deserializer);

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  IrcEvent sse_decode_irc_event(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MemberView> sse_decode_list_member_view(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RemovedItem> sse_decode_list_removed_item(SseDeserializer deserializer);

  @protected
  List<TextSpan> sse_decode_list_text_span(SseDeserializer deserializer);

  @protected
  MemberView sse_decode_member_view(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ProxyConfig? sse_decode_opt_box_autoadd_proxy_config(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  ProxyConfig sse_decode_proxy_config(SseDeserializer deserializer);

  @protected
  RemovedItem sse_decode_removed_item(SseDeserializer deserializer);

  @protected
  ServerConfig sse_decode_server_config(SseDeserializer deserializer);

  @protected
  SpanStyle sse_decode_span_style(SseDeserializer deserializer);

  @protected
  Target sse_decode_target(SseDeserializer deserializer);

  @protected
  TextSpan sse_decode_text_span(SseDeserializer deserializer);

  @protected
  TorStatus sse_decode_tor_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_irc_event_Sse(
    RustStreamSink<IrcEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tor_status_Sse(
    RustStreamSink<TorStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_outcome(AuthOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_auth_outcome(
    AuthOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_chat_message(
    ChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proxy_config(
    ProxyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_server_config(
    ServerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_clean_outcome(CleanOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_irc_event(IrcEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_member_view(
    List<MemberView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_removed_item(
    List<RemovedItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_text_span(List<TextSpan> self, SseSerializer serializer);

  @protected
  void sse_encode_member_view(MemberView self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_proxy_config(
    ProxyConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_config(ProxyConfig self, SseSerializer serializer);

  @protected
  void sse_encode_removed_item(RemovedItem self, SseSerializer serializer);

  @protected
  void sse_encode_server_config(ServerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_span_style(SpanStyle self, SseSerializer serializer);

  @protected
  void sse_encode_target(Target self, SseSerializer serializer);

  @protected
  void sse_encode_text_span(TextSpan self, SseSerializer serializer);

  @protected
  void sse_encode_tor_status(TorStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
