// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'api/server.dart';
import 'api/tor.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1274361068;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ddirc_bridge',
        ioDirectory: 'irc-core/ddirc-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiClientAcceptFile({
    required BigInt id,
    required BigInt transferId,
    required String directory,
  });

  Future<void> crateApiClientCancelTransfer({
    required BigInt id,
    required BigInt transferId,
  });

  Future<CleanOutcome> crateApiClientCleanMedia({required List<int> bytes});

  Future<BigInt> crateApiClientConnect({required ServerConfig config});

  int crateApiClientDefaultTlsPort();

  Future<void> crateApiClientDisconnect({required BigInt id, String? reason});

  Stream<IrcEvent> crateApiClientEventStream({required BigInt id});

  Future<void> crateApiInitApp();

  Future<void> crateApiClientJoin({
    required BigInt id,
    required String channel,
    String? key,
  });

  Future<void> crateApiClientListChannels({required BigInt id});

  Future<LocalServerInfo?> crateApiServerLocalServerInfo();

  Future<LocalServerInfo> crateApiServerLocalServerStart({
    required String dataDir,
  });

  Future<void> crateApiServerLocalServerStop();

  Future<void> crateApiClientPart({
    required BigInt id,
    required String channel,
    String? reason,
  });

  Future<void> crateApiClientReconnect({required BigInt id});

  Future<void> crateApiClientSendAction({
    required BigInt id,
    required String target,
    required String text,
  });

  Future<void> crateApiClientSendFile({
    required BigInt id,
    required String target,
    required String path,
  });

  Future<void> crateApiClientSendMessage({
    required BigInt id,
    required String target,
    required String text,
  });

  Future<void> crateApiClientSetNick({
    required BigInt id,
    required String nick,
  });

  Future<void> crateApiClientSetTopic({
    required BigInt id,
    required String channel,
    required String topic,
  });

  Future<int?> crateApiTorTorPort();

  int crateApiClientTorSocksPort();

  Future<int> crateApiTorTorStart({required String dataDir});

  Stream<TorStatus> crateApiTorTorStatusStream();

  Future<void> crateApiTorTorStop();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiClientAcceptFile({
    required BigInt id,
    required BigInt transferId,
    required String directory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_u_64(transferId, serializer);
          sse_encode_String(directory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientAcceptFileConstMeta,
        argValues: [id, transferId, directory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientAcceptFileConstMeta => const TaskConstMeta(
    debugName: "accept_file",
    argNames: ["id", "transferId", "directory"],
  );

  @override
  Future<void> crateApiClientCancelTransfer({
    required BigInt id,
    required BigInt transferId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_u_64(transferId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientCancelTransferConstMeta,
        argValues: [id, transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientCancelTransferConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_transfer",
        argNames: ["id", "transferId"],
      );

  @override
  Future<CleanOutcome> crateApiClientCleanMedia({required List<int> bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_clean_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientCleanMediaConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientCleanMediaConstMeta =>
      const TaskConstMeta(debugName: "clean_media", argNames: ["bytes"]);

  @override
  Future<BigInt> crateApiClientConnect({required ServerConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_server_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientConnectConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientConnectConstMeta =>
      const TaskConstMeta(debugName: "connect", argNames: ["config"]);

  @override
  int crateApiClientDefaultTlsPort() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientDefaultTlsPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientDefaultTlsPortConstMeta =>
      const TaskConstMeta(debugName: "default_tls_port", argNames: []);

  @override
  Future<void> crateApiClientDisconnect({required BigInt id, String? reason}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_opt_String(reason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientDisconnectConstMeta,
        argValues: [id, reason],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: ["id", "reason"]);

  @override
  Stream<IrcEvent> crateApiClientEventStream({required BigInt id}) {
    final sink = RustStreamSink<IrcEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_64(id, serializer);
            sse_encode_StreamSink_irc_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiClientEventStreamConstMeta,
          argValues: [id, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientEventStreamConstMeta =>
      const TaskConstMeta(debugName: "event_stream", argNames: ["id", "sink"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiClientJoin({
    required BigInt id,
    required String channel,
    String? key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(channel, serializer);
          sse_encode_opt_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientJoinConstMeta,
        argValues: [id, channel, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientJoinConstMeta => const TaskConstMeta(
    debugName: "join",
    argNames: ["id", "channel", "key"],
  );

  @override
  Future<void> crateApiClientListChannels({required BigInt id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientListChannelsConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientListChannelsConstMeta =>
      const TaskConstMeta(debugName: "list_channels", argNames: ["id"]);

  @override
  Future<LocalServerInfo?> crateApiServerLocalServerInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_local_server_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiServerLocalServerInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServerLocalServerInfoConstMeta =>
      const TaskConstMeta(debugName: "local_server_info", argNames: []);

  @override
  Future<LocalServerInfo> crateApiServerLocalServerStart({
    required String dataDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_local_server_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiServerLocalServerStartConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServerLocalServerStartConstMeta =>
      const TaskConstMeta(
        debugName: "local_server_start",
        argNames: ["dataDir"],
      );

  @override
  Future<void> crateApiServerLocalServerStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiServerLocalServerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiServerLocalServerStopConstMeta =>
      const TaskConstMeta(debugName: "local_server_stop", argNames: []);

  @override
  Future<void> crateApiClientPart({
    required BigInt id,
    required String channel,
    String? reason,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(channel, serializer);
          sse_encode_opt_String(reason, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientPartConstMeta,
        argValues: [id, channel, reason],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientPartConstMeta => const TaskConstMeta(
    debugName: "part",
    argNames: ["id", "channel", "reason"],
  );

  @override
  Future<void> crateApiClientReconnect({required BigInt id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientReconnectConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientReconnectConstMeta =>
      const TaskConstMeta(debugName: "reconnect", argNames: ["id"]);

  @override
  Future<void> crateApiClientSendAction({
    required BigInt id,
    required String target,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(target, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientSendActionConstMeta,
        argValues: [id, target, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSendActionConstMeta => const TaskConstMeta(
    debugName: "send_action",
    argNames: ["id", "target", "text"],
  );

  @override
  Future<void> crateApiClientSendFile({
    required BigInt id,
    required String target,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(target, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientSendFileConstMeta,
        argValues: [id, target, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSendFileConstMeta => const TaskConstMeta(
    debugName: "send_file",
    argNames: ["id", "target", "path"],
  );

  @override
  Future<void> crateApiClientSendMessage({
    required BigInt id,
    required String target,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(target, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientSendMessageConstMeta,
        argValues: [id, target, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["id", "target", "text"],
  );

  @override
  Future<void> crateApiClientSetNick({
    required BigInt id,
    required String nick,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(nick, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientSetNickConstMeta,
        argValues: [id, nick],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSetNickConstMeta =>
      const TaskConstMeta(debugName: "set_nick", argNames: ["id", "nick"]);

  @override
  Future<void> crateApiClientSetTopic({
    required BigInt id,
    required String channel,
    required String topic,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(id, serializer);
          sse_encode_String(channel, serializer);
          sse_encode_String(topic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClientSetTopicConstMeta,
        argValues: [id, channel, topic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSetTopicConstMeta => const TaskConstMeta(
    debugName: "set_topic",
    argNames: ["id", "channel", "topic"],
  );

  @override
  Future<int?> crateApiTorTorPort() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorTorPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorTorPortConstMeta =>
      const TaskConstMeta(debugName: "tor_port", argNames: []);

  @override
  int crateApiClientTorSocksPort() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClientTorSocksPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientTorSocksPortConstMeta =>
      const TaskConstMeta(debugName: "tor_socks_port", argNames: []);

  @override
  Future<int> crateApiTorTorStart({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTorTorStartConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorTorStartConstMeta =>
      const TaskConstMeta(debugName: "tor_start", argNames: ["dataDir"]);

  @override
  Stream<TorStatus> crateApiTorTorStatusStream() {
    final sink = RustStreamSink<TorStatus>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_tor_status_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 24,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiTorTorStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTorTorStatusStreamConstMeta =>
      const TaskConstMeta(debugName: "tor_status_stream", argNames: ["sink"]);

  @override
  Future<void> crateApiTorTorStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTorTorStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTorTorStopConstMeta =>
      const TaskConstMeta(debugName: "tor_stop", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<IrcEvent> dco_decode_StreamSink_irc_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TorStatus> dco_decode_StreamSink_tor_status_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthOutcome dco_decode_auth_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AuthOutcome_Sasl();
      case 1:
        return AuthOutcome_NickServFallback(reason: dco_decode_String(raw[1]));
      case 2:
        return AuthOutcome_Anonymous();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AuthOutcome dco_decode_box_autoadd_auth_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_auth_outcome(raw);
  }

  @protected
  ChatMessage dco_decode_box_autoadd_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chat_message(raw);
  }

  @protected
  ConnectionStatus dco_decode_box_autoadd_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_connection_status(raw);
  }

  @protected
  DccOffer dco_decode_box_autoadd_dcc_offer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dcc_offer(raw);
  }

  @protected
  LocalServerInfo dco_decode_box_autoadd_local_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_local_server_info(raw);
  }

  @protected
  MemberView dco_decode_box_autoadd_member_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_member_view(raw);
  }

  @protected
  ProxyConfig dco_decode_box_autoadd_proxy_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_proxy_config(raw);
  }

  @protected
  ServerConfig dco_decode_box_autoadd_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_server_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ChannelListing dco_decode_channel_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChannelListing(
      name: dco_decode_String(arr[0]),
      users: dco_decode_u_32(arr[1]),
      topic: dco_decode_String(arr[2]),
    );
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ChatMessage(
      target: dco_decode_target(arr[0]),
      sender: dco_decode_String(arr[1]),
      senderPrefix: dco_decode_opt_String(arr[2]),
      spans: dco_decode_list_text_span(arr[3]),
      isSelf: dco_decode_bool(arr[4]),
      isMention: dco_decode_bool(arr[5]),
      isAction: dco_decode_bool(arr[6]),
      isNotice: dco_decode_bool(arr[7]),
    );
  }

  @protected
  CleanOutcome dco_decode_clean_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CleanOutcome_Cleaned(
          bytes: dco_decode_list_prim_u_8_strict(raw[1]),
          kind: dco_decode_String(raw[2]),
          removed: dco_decode_list_removed_item(raw[3]),
        );
      case 1:
        return CleanOutcome_AlreadyClean(kind: dco_decode_String(raw[1]));
      case 2:
        return CleanOutcome_NotAnImage();
      case 3:
        return CleanOutcome_Malformed(detail: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ConnectionStatus_Disconnected();
      case 1:
        return ConnectionStatus_Connecting();
      case 2:
        return ConnectionStatus_Registering();
      case 3:
        return ConnectionStatus_Connected();
      case 4:
        return ConnectionStatus_Reconnecting(
          retryInSecs: dco_decode_u_64(raw[1]),
          attempt: dco_decode_u_32(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DccOffer dco_decode_dcc_offer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DccOffer(
      filename: dco_decode_String(arr[0]),
      host: dco_decode_opt_String(arr[1]),
      port: dco_decode_opt_box_autoadd_u_16(arr[2]),
      size: dco_decode_opt_box_autoadd_u_64(arr[3]),
      token: dco_decode_opt_box_autoadd_u_64(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  IrcEvent dco_decode_irc_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return IrcEvent_Status(
          status: dco_decode_box_autoadd_connection_status(raw[1]),
          detail: dco_decode_opt_String(raw[2]),
        );
      case 1:
        return IrcEvent_Registered(
          nick: dco_decode_String(raw[1]),
          network: dco_decode_opt_String(raw[2]),
          auth: dco_decode_box_autoadd_auth_outcome(raw[3]),
        );
      case 2:
        return IrcEvent_NetworkNamed(network: dco_decode_String(raw[1]));
      case 3:
        return IrcEvent_Message(
          message: dco_decode_box_autoadd_chat_message(raw[1]),
        );
      case 4:
        return IrcEvent_Joined(
          channel: dco_decode_String(raw[1]),
          nick: dco_decode_String(raw[2]),
          isSelf: dco_decode_bool(raw[3]),
        );
      case 5:
        return IrcEvent_Parted(
          channel: dco_decode_String(raw[1]),
          nick: dco_decode_String(raw[2]),
          isSelf: dco_decode_bool(raw[3]),
          reason: dco_decode_opt_String(raw[4]),
        );
      case 6:
        return IrcEvent_Quit(
          channel: dco_decode_String(raw[1]),
          nick: dco_decode_String(raw[2]),
          reason: dco_decode_opt_String(raw[3]),
        );
      case 7:
        return IrcEvent_NickChanged(
          channel: dco_decode_String(raw[1]),
          old: dco_decode_String(raw[2]),
          new_: dco_decode_String(raw[3]),
          isSelf: dco_decode_bool(raw[4]),
        );
      case 8:
        return IrcEvent_TopicChanged(
          channel: dco_decode_String(raw[1]),
          topic: dco_decode_String(raw[2]),
          setBy: dco_decode_opt_String(raw[3]),
        );
      case 9:
        return IrcEvent_MemberList(
          channel: dco_decode_String(raw[1]),
          members: dco_decode_list_member_view(raw[2]),
        );
      case 10:
        return IrcEvent_MemberChanged(
          channel: dco_decode_String(raw[1]),
          previous: dco_decode_String(raw[2]),
          member: dco_decode_opt_box_autoadd_member_view(raw[3]),
        );
      case 11:
        return IrcEvent_ModeChanged(
          channel: dco_decode_String(raw[1]),
          by: dco_decode_opt_String(raw[2]),
          affected: dco_decode_list_String(raw[3]),
        );
      case 12:
        return IrcEvent_MessagesDropped(
          channel: dco_decode_opt_String(raw[1]),
          count: dco_decode_u_64(raw[2]),
        );
      case 13:
        return IrcEvent_FileOffered(
          id: dco_decode_u_64(raw[1]),
          channel: dco_decode_String(raw[2]),
          from: dco_decode_String(raw[3]),
          offer: dco_decode_box_autoadd_dcc_offer(raw[4]),
        );
      case 14:
        return IrcEvent_FileTransferStarted(
          id: dco_decode_u_64(raw[1]),
          channel: dco_decode_String(raw[2]),
          filename: dco_decode_String(raw[3]),
          incoming: dco_decode_bool(raw[4]),
          total: dco_decode_opt_box_autoadd_u_64(raw[5]),
        );
      case 15:
        return IrcEvent_FileTransferProgress(
          id: dco_decode_u_64(raw[1]),
          transferred: dco_decode_u_64(raw[2]),
        );
      case 16:
        return IrcEvent_FileTransferEnded(
          id: dco_decode_u_64(raw[1]),
          channel: dco_decode_String(raw[2]),
          filename: dco_decode_String(raw[3]),
          path: dco_decode_opt_String(raw[4]),
          error: dco_decode_opt_String(raw[5]),
        );
      case 17:
        return IrcEvent_ChannelList(
          channels: dco_decode_list_channel_listing(raw[1]),
          done: dco_decode_bool(raw[2]),
          truncated: dco_decode_bool(raw[3]),
        );
      case 18:
        return IrcEvent_Error(
          message: dco_decode_String(raw[1]),
          fatal: dco_decode_bool(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChannelListing> dco_decode_list_channel_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_channel_listing).toList();
  }

  @protected
  List<MemberView> dco_decode_list_member_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_view).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RemovedItem> dco_decode_list_removed_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_removed_item).toList();
  }

  @protected
  List<TextSpan> dco_decode_list_text_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_text_span).toList();
  }

  @protected
  LocalServerInfo dco_decode_local_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LocalServerInfo(
      port: dco_decode_u_16(arr[0]),
      serverName: dco_decode_String(arr[1]),
      networkName: dco_decode_String(arr[2]),
    );
  }

  @protected
  MemberView dco_decode_member_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MemberView(
      nick: dco_decode_String(arr[0]),
      prefix: dco_decode_opt_String(arr[1]),
      away: dco_decode_bool(arr[2]),
      sortKey: dco_decode_String(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  LocalServerInfo? dco_decode_opt_box_autoadd_local_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_local_server_info(raw);
  }

  @protected
  MemberView? dco_decode_opt_box_autoadd_member_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_member_view(raw);
  }

  @protected
  ProxyConfig? dco_decode_opt_box_autoadd_proxy_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_proxy_config(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  ProxyConfig dco_decode_proxy_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProxyConfig(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      username: dco_decode_opt_String(arr[2]),
      password: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  RemovedItem dco_decode_removed_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RemovedItem(
      what: dco_decode_String(arr[0]),
      bytes: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  ServerConfig dco_decode_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ServerConfig(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      nickname: dco_decode_String(arr[2]),
      altNicks: dco_decode_list_String(arr[3]),
      username: dco_decode_opt_String(arr[4]),
      realname: dco_decode_opt_String(arr[5]),
      channels: dco_decode_list_String(arr[6]),
      saslAccount: dco_decode_opt_String(arr[7]),
      saslPassword: dco_decode_opt_String(arr[8]),
      nickservPassword: dco_decode_opt_String(arr[9]),
      serverPassword: dco_decode_opt_String(arr[10]),
      proxy: dco_decode_opt_box_autoadd_proxy_config(arr[11]),
    );
  }

  @protected
  SpanStyle dco_decode_span_style(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SpanStyle(
      bold: dco_decode_bool(arr[0]),
      italic: dco_decode_bool(arr[1]),
      underline: dco_decode_bool(arr[2]),
      strikethrough: dco_decode_bool(arr[3]),
      monospace: dco_decode_bool(arr[4]),
      inverse: dco_decode_bool(arr[5]),
      fg: dco_decode_opt_box_autoadd_u_8(arr[6]),
      bg: dco_decode_opt_box_autoadd_u_8(arr[7]),
    );
  }

  @protected
  Target dco_decode_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Target_Channel(name: dco_decode_String(raw[1]));
      case 1:
        return Target_Direct(nick: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TextSpan dco_decode_text_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TextSpan(
      text: dco_decode_String(arr[0]),
      style: dco_decode_span_style(arr[1]),
    );
  }

  @protected
  TorStatus dco_decode_tor_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TorStatus(
      ready: dco_decode_bool(arr[0]),
      progress: dco_decode_f_32(arr[1]),
      summary: dco_decode_String(arr[2]),
      blocked: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<IrcEvent> sse_decode_StreamSink_irc_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TorStatus> sse_decode_StreamSink_tor_status_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthOutcome sse_decode_auth_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return AuthOutcome_Sasl();
      case 1:
        var var_reason = sse_decode_String(deserializer);
        return AuthOutcome_NickServFallback(reason: var_reason);
      case 2:
        return AuthOutcome_Anonymous();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AuthOutcome sse_decode_box_autoadd_auth_outcome(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_auth_outcome(deserializer));
  }

  @protected
  ChatMessage sse_decode_box_autoadd_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chat_message(deserializer));
  }

  @protected
  ConnectionStatus sse_decode_box_autoadd_connection_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_connection_status(deserializer));
  }

  @protected
  DccOffer sse_decode_box_autoadd_dcc_offer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dcc_offer(deserializer));
  }

  @protected
  LocalServerInfo sse_decode_box_autoadd_local_server_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_local_server_info(deserializer));
  }

  @protected
  MemberView sse_decode_box_autoadd_member_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_member_view(deserializer));
  }

  @protected
  ProxyConfig sse_decode_box_autoadd_proxy_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_proxy_config(deserializer));
  }

  @protected
  ServerConfig sse_decode_box_autoadd_server_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_server_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  ChannelListing sse_decode_channel_listing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_users = sse_decode_u_32(deserializer);
    var var_topic = sse_decode_String(deserializer);
    return ChannelListing(name: var_name, users: var_users, topic: var_topic);
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_target = sse_decode_target(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_senderPrefix = sse_decode_opt_String(deserializer);
    var var_spans = sse_decode_list_text_span(deserializer);
    var var_isSelf = sse_decode_bool(deserializer);
    var var_isMention = sse_decode_bool(deserializer);
    var var_isAction = sse_decode_bool(deserializer);
    var var_isNotice = sse_decode_bool(deserializer);
    return ChatMessage(
      target: var_target,
      sender: var_sender,
      senderPrefix: var_senderPrefix,
      spans: var_spans,
      isSelf: var_isSelf,
      isMention: var_isMention,
      isAction: var_isAction,
      isNotice: var_isNotice,
    );
  }

  @protected
  CleanOutcome sse_decode_clean_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
        var var_kind = sse_decode_String(deserializer);
        var var_removed = sse_decode_list_removed_item(deserializer);
        return CleanOutcome_Cleaned(
          bytes: var_bytes,
          kind: var_kind,
          removed: var_removed,
        );
      case 1:
        var var_kind = sse_decode_String(deserializer);
        return CleanOutcome_AlreadyClean(kind: var_kind);
      case 2:
        return CleanOutcome_NotAnImage();
      case 3:
        var var_detail = sse_decode_String(deserializer);
        return CleanOutcome_Malformed(detail: var_detail);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ConnectionStatus_Disconnected();
      case 1:
        return ConnectionStatus_Connecting();
      case 2:
        return ConnectionStatus_Registering();
      case 3:
        return ConnectionStatus_Connected();
      case 4:
        var var_retryInSecs = sse_decode_u_64(deserializer);
        var var_attempt = sse_decode_u_32(deserializer);
        return ConnectionStatus_Reconnecting(
          retryInSecs: var_retryInSecs,
          attempt: var_attempt,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DccOffer sse_decode_dcc_offer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filename = sse_decode_String(deserializer);
    var var_host = sse_decode_opt_String(deserializer);
    var var_port = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_size = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_token = sse_decode_opt_box_autoadd_u_64(deserializer);
    return DccOffer(
      filename: var_filename,
      host: var_host,
      port: var_port,
      size: var_size,
      token: var_token,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  IrcEvent sse_decode_irc_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_status = sse_decode_box_autoadd_connection_status(deserializer);
        var var_detail = sse_decode_opt_String(deserializer);
        return IrcEvent_Status(status: var_status, detail: var_detail);
      case 1:
        var var_nick = sse_decode_String(deserializer);
        var var_network = sse_decode_opt_String(deserializer);
        var var_auth = sse_decode_box_autoadd_auth_outcome(deserializer);
        return IrcEvent_Registered(
          nick: var_nick,
          network: var_network,
          auth: var_auth,
        );
      case 2:
        var var_network = sse_decode_String(deserializer);
        return IrcEvent_NetworkNamed(network: var_network);
      case 3:
        var var_message = sse_decode_box_autoadd_chat_message(deserializer);
        return IrcEvent_Message(message: var_message);
      case 4:
        var var_channel = sse_decode_String(deserializer);
        var var_nick = sse_decode_String(deserializer);
        var var_isSelf = sse_decode_bool(deserializer);
        return IrcEvent_Joined(
          channel: var_channel,
          nick: var_nick,
          isSelf: var_isSelf,
        );
      case 5:
        var var_channel = sse_decode_String(deserializer);
        var var_nick = sse_decode_String(deserializer);
        var var_isSelf = sse_decode_bool(deserializer);
        var var_reason = sse_decode_opt_String(deserializer);
        return IrcEvent_Parted(
          channel: var_channel,
          nick: var_nick,
          isSelf: var_isSelf,
          reason: var_reason,
        );
      case 6:
        var var_channel = sse_decode_String(deserializer);
        var var_nick = sse_decode_String(deserializer);
        var var_reason = sse_decode_opt_String(deserializer);
        return IrcEvent_Quit(
          channel: var_channel,
          nick: var_nick,
          reason: var_reason,
        );
      case 7:
        var var_channel = sse_decode_String(deserializer);
        var var_old = sse_decode_String(deserializer);
        var var_new_ = sse_decode_String(deserializer);
        var var_isSelf = sse_decode_bool(deserializer);
        return IrcEvent_NickChanged(
          channel: var_channel,
          old: var_old,
          new_: var_new_,
          isSelf: var_isSelf,
        );
      case 8:
        var var_channel = sse_decode_String(deserializer);
        var var_topic = sse_decode_String(deserializer);
        var var_setBy = sse_decode_opt_String(deserializer);
        return IrcEvent_TopicChanged(
          channel: var_channel,
          topic: var_topic,
          setBy: var_setBy,
        );
      case 9:
        var var_channel = sse_decode_String(deserializer);
        var var_members = sse_decode_list_member_view(deserializer);
        return IrcEvent_MemberList(channel: var_channel, members: var_members);
      case 10:
        var var_channel = sse_decode_String(deserializer);
        var var_previous = sse_decode_String(deserializer);
        var var_member = sse_decode_opt_box_autoadd_member_view(deserializer);
        return IrcEvent_MemberChanged(
          channel: var_channel,
          previous: var_previous,
          member: var_member,
        );
      case 11:
        var var_channel = sse_decode_String(deserializer);
        var var_by = sse_decode_opt_String(deserializer);
        var var_affected = sse_decode_list_String(deserializer);
        return IrcEvent_ModeChanged(
          channel: var_channel,
          by: var_by,
          affected: var_affected,
        );
      case 12:
        var var_channel = sse_decode_opt_String(deserializer);
        var var_count = sse_decode_u_64(deserializer);
        return IrcEvent_MessagesDropped(channel: var_channel, count: var_count);
      case 13:
        var var_id = sse_decode_u_64(deserializer);
        var var_channel = sse_decode_String(deserializer);
        var var_from = sse_decode_String(deserializer);
        var var_offer = sse_decode_box_autoadd_dcc_offer(deserializer);
        return IrcEvent_FileOffered(
          id: var_id,
          channel: var_channel,
          from: var_from,
          offer: var_offer,
        );
      case 14:
        var var_id = sse_decode_u_64(deserializer);
        var var_channel = sse_decode_String(deserializer);
        var var_filename = sse_decode_String(deserializer);
        var var_incoming = sse_decode_bool(deserializer);
        var var_total = sse_decode_opt_box_autoadd_u_64(deserializer);
        return IrcEvent_FileTransferStarted(
          id: var_id,
          channel: var_channel,
          filename: var_filename,
          incoming: var_incoming,
          total: var_total,
        );
      case 15:
        var var_id = sse_decode_u_64(deserializer);
        var var_transferred = sse_decode_u_64(deserializer);
        return IrcEvent_FileTransferProgress(
          id: var_id,
          transferred: var_transferred,
        );
      case 16:
        var var_id = sse_decode_u_64(deserializer);
        var var_channel = sse_decode_String(deserializer);
        var var_filename = sse_decode_String(deserializer);
        var var_path = sse_decode_opt_String(deserializer);
        var var_error = sse_decode_opt_String(deserializer);
        return IrcEvent_FileTransferEnded(
          id: var_id,
          channel: var_channel,
          filename: var_filename,
          path: var_path,
          error: var_error,
        );
      case 17:
        var var_channels = sse_decode_list_channel_listing(deserializer);
        var var_done = sse_decode_bool(deserializer);
        var var_truncated = sse_decode_bool(deserializer);
        return IrcEvent_ChannelList(
          channels: var_channels,
          done: var_done,
          truncated: var_truncated,
        );
      case 18:
        var var_message = sse_decode_String(deserializer);
        var var_fatal = sse_decode_bool(deserializer);
        return IrcEvent_Error(message: var_message, fatal: var_fatal);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChannelListing> sse_decode_list_channel_listing(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChannelListing>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_channel_listing(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberView> sse_decode_list_member_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RemovedItem> sse_decode_list_removed_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RemovedItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_removed_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<TextSpan> sse_decode_list_text_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TextSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_text_span(deserializer));
    }
    return ans_;
  }

  @protected
  LocalServerInfo sse_decode_local_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_port = sse_decode_u_16(deserializer);
    var var_serverName = sse_decode_String(deserializer);
    var var_networkName = sse_decode_String(deserializer);
    return LocalServerInfo(
      port: var_port,
      serverName: var_serverName,
      networkName: var_networkName,
    );
  }

  @protected
  MemberView sse_decode_member_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nick = sse_decode_String(deserializer);
    var var_prefix = sse_decode_opt_String(deserializer);
    var var_away = sse_decode_bool(deserializer);
    var var_sortKey = sse_decode_String(deserializer);
    return MemberView(
      nick: var_nick,
      prefix: var_prefix,
      away: var_away,
      sortKey: var_sortKey,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LocalServerInfo? sse_decode_opt_box_autoadd_local_server_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_local_server_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MemberView? sse_decode_opt_box_autoadd_member_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_member_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProxyConfig? sse_decode_opt_box_autoadd_proxy_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_proxy_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProxyConfig sse_decode_proxy_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    return ProxyConfig(
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
    );
  }

  @protected
  RemovedItem sse_decode_removed_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_what = sse_decode_String(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    return RemovedItem(what: var_what, bytes: var_bytes);
  }

  @protected
  ServerConfig sse_decode_server_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_nickname = sse_decode_String(deserializer);
    var var_altNicks = sse_decode_list_String(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_realname = sse_decode_opt_String(deserializer);
    var var_channels = sse_decode_list_String(deserializer);
    var var_saslAccount = sse_decode_opt_String(deserializer);
    var var_saslPassword = sse_decode_opt_String(deserializer);
    var var_nickservPassword = sse_decode_opt_String(deserializer);
    var var_serverPassword = sse_decode_opt_String(deserializer);
    var var_proxy = sse_decode_opt_box_autoadd_proxy_config(deserializer);
    return ServerConfig(
      host: var_host,
      port: var_port,
      nickname: var_nickname,
      altNicks: var_altNicks,
      username: var_username,
      realname: var_realname,
      channels: var_channels,
      saslAccount: var_saslAccount,
      saslPassword: var_saslPassword,
      nickservPassword: var_nickservPassword,
      serverPassword: var_serverPassword,
      proxy: var_proxy,
    );
  }

  @protected
  SpanStyle sse_decode_span_style(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bold = sse_decode_bool(deserializer);
    var var_italic = sse_decode_bool(deserializer);
    var var_underline = sse_decode_bool(deserializer);
    var var_strikethrough = sse_decode_bool(deserializer);
    var var_monospace = sse_decode_bool(deserializer);
    var var_inverse = sse_decode_bool(deserializer);
    var var_fg = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_bg = sse_decode_opt_box_autoadd_u_8(deserializer);
    return SpanStyle(
      bold: var_bold,
      italic: var_italic,
      underline: var_underline,
      strikethrough: var_strikethrough,
      monospace: var_monospace,
      inverse: var_inverse,
      fg: var_fg,
      bg: var_bg,
    );
  }

  @protected
  Target sse_decode_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_name = sse_decode_String(deserializer);
        return Target_Channel(name: var_name);
      case 1:
        var var_nick = sse_decode_String(deserializer);
        return Target_Direct(nick: var_nick);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TextSpan sse_decode_text_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_style = sse_decode_span_style(deserializer);
    return TextSpan(text: var_text, style: var_style);
  }

  @protected
  TorStatus sse_decode_tor_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ready = sse_decode_bool(deserializer);
    var var_progress = sse_decode_f_32(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_blocked = sse_decode_opt_String(deserializer);
    return TorStatus(
      ready: var_ready,
      progress: var_progress,
      summary: var_summary,
      blocked: var_blocked,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_irc_event_Sse(
    RustStreamSink<IrcEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_irc_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_tor_status_Sse(
    RustStreamSink<TorStatus> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_tor_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_outcome(AuthOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AuthOutcome_Sasl():
        sse_encode_i_32(0, serializer);
      case AuthOutcome_NickServFallback(reason: final reason):
        sse_encode_i_32(1, serializer);
        sse_encode_String(reason, serializer);
      case AuthOutcome_Anonymous():
        sse_encode_i_32(2, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_auth_outcome(
    AuthOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_auth_outcome(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_chat_message(
    ChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chat_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_connection_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dcc_offer(
    DccOffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dcc_offer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_local_server_info(
    LocalServerInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_local_server_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_member_view(
    MemberView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_member_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_proxy_config(
    ProxyConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_proxy_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_server_config(
    ServerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_channel_listing(
    ChannelListing self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.users, serializer);
    sse_encode_String(self.topic, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_target(self.target, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_opt_String(self.senderPrefix, serializer);
    sse_encode_list_text_span(self.spans, serializer);
    sse_encode_bool(self.isSelf, serializer);
    sse_encode_bool(self.isMention, serializer);
    sse_encode_bool(self.isAction, serializer);
    sse_encode_bool(self.isNotice, serializer);
  }

  @protected
  void sse_encode_clean_outcome(CleanOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CleanOutcome_Cleaned(
        bytes: final bytes,
        kind: final kind,
        removed: final removed,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_list_prim_u_8_strict(bytes, serializer);
        sse_encode_String(kind, serializer);
        sse_encode_list_removed_item(removed, serializer);
      case CleanOutcome_AlreadyClean(kind: final kind):
        sse_encode_i_32(1, serializer);
        sse_encode_String(kind, serializer);
      case CleanOutcome_NotAnImage():
        sse_encode_i_32(2, serializer);
      case CleanOutcome_Malformed(detail: final detail):
        sse_encode_i_32(3, serializer);
        sse_encode_String(detail, serializer);
    }
  }

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ConnectionStatus_Disconnected():
        sse_encode_i_32(0, serializer);
      case ConnectionStatus_Connecting():
        sse_encode_i_32(1, serializer);
      case ConnectionStatus_Registering():
        sse_encode_i_32(2, serializer);
      case ConnectionStatus_Connected():
        sse_encode_i_32(3, serializer);
      case ConnectionStatus_Reconnecting(
        retryInSecs: final retryInSecs,
        attempt: final attempt,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_u_64(retryInSecs, serializer);
        sse_encode_u_32(attempt, serializer);
    }
  }

  @protected
  void sse_encode_dcc_offer(DccOffer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filename, serializer);
    sse_encode_opt_String(self.host, serializer);
    sse_encode_opt_box_autoadd_u_16(self.port, serializer);
    sse_encode_opt_box_autoadd_u_64(self.size, serializer);
    sse_encode_opt_box_autoadd_u_64(self.token, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_irc_event(IrcEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case IrcEvent_Status(status: final status, detail: final detail):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_connection_status(status, serializer);
        sse_encode_opt_String(detail, serializer);
      case IrcEvent_Registered(
        nick: final nick,
        network: final network,
        auth: final auth,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(nick, serializer);
        sse_encode_opt_String(network, serializer);
        sse_encode_box_autoadd_auth_outcome(auth, serializer);
      case IrcEvent_NetworkNamed(network: final network):
        sse_encode_i_32(2, serializer);
        sse_encode_String(network, serializer);
      case IrcEvent_Message(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_chat_message(message, serializer);
      case IrcEvent_Joined(
        channel: final channel,
        nick: final nick,
        isSelf: final isSelf,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(nick, serializer);
        sse_encode_bool(isSelf, serializer);
      case IrcEvent_Parted(
        channel: final channel,
        nick: final nick,
        isSelf: final isSelf,
        reason: final reason,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(nick, serializer);
        sse_encode_bool(isSelf, serializer);
        sse_encode_opt_String(reason, serializer);
      case IrcEvent_Quit(
        channel: final channel,
        nick: final nick,
        reason: final reason,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(nick, serializer);
        sse_encode_opt_String(reason, serializer);
      case IrcEvent_NickChanged(
        channel: final channel,
        old: final old,
        new_: final new_,
        isSelf: final isSelf,
      ):
        sse_encode_i_32(7, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(old, serializer);
        sse_encode_String(new_, serializer);
        sse_encode_bool(isSelf, serializer);
      case IrcEvent_TopicChanged(
        channel: final channel,
        topic: final topic,
        setBy: final setBy,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(topic, serializer);
        sse_encode_opt_String(setBy, serializer);
      case IrcEvent_MemberList(channel: final channel, members: final members):
        sse_encode_i_32(9, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_list_member_view(members, serializer);
      case IrcEvent_MemberChanged(
        channel: final channel,
        previous: final previous,
        member: final member,
      ):
        sse_encode_i_32(10, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(previous, serializer);
        sse_encode_opt_box_autoadd_member_view(member, serializer);
      case IrcEvent_ModeChanged(
        channel: final channel,
        by: final by,
        affected: final affected,
      ):
        sse_encode_i_32(11, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_opt_String(by, serializer);
        sse_encode_list_String(affected, serializer);
      case IrcEvent_MessagesDropped(channel: final channel, count: final count):
        sse_encode_i_32(12, serializer);
        sse_encode_opt_String(channel, serializer);
        sse_encode_u_64(count, serializer);
      case IrcEvent_FileOffered(
        id: final id,
        channel: final channel,
        from: final from,
        offer: final offer,
      ):
        sse_encode_i_32(13, serializer);
        sse_encode_u_64(id, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(from, serializer);
        sse_encode_box_autoadd_dcc_offer(offer, serializer);
      case IrcEvent_FileTransferStarted(
        id: final id,
        channel: final channel,
        filename: final filename,
        incoming: final incoming,
        total: final total,
      ):
        sse_encode_i_32(14, serializer);
        sse_encode_u_64(id, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_bool(incoming, serializer);
        sse_encode_opt_box_autoadd_u_64(total, serializer);
      case IrcEvent_FileTransferProgress(
        id: final id,
        transferred: final transferred,
      ):
        sse_encode_i_32(15, serializer);
        sse_encode_u_64(id, serializer);
        sse_encode_u_64(transferred, serializer);
      case IrcEvent_FileTransferEnded(
        id: final id,
        channel: final channel,
        filename: final filename,
        path: final path,
        error: final error,
      ):
        sse_encode_i_32(16, serializer);
        sse_encode_u_64(id, serializer);
        sse_encode_String(channel, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_opt_String(path, serializer);
        sse_encode_opt_String(error, serializer);
      case IrcEvent_ChannelList(
        channels: final channels,
        done: final done,
        truncated: final truncated,
      ):
        sse_encode_i_32(17, serializer);
        sse_encode_list_channel_listing(channels, serializer);
        sse_encode_bool(done, serializer);
        sse_encode_bool(truncated, serializer);
      case IrcEvent_Error(message: final message, fatal: final fatal):
        sse_encode_i_32(18, serializer);
        sse_encode_String(message, serializer);
        sse_encode_bool(fatal, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_channel_listing(
    List<ChannelListing> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_channel_listing(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_view(
    List<MemberView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_removed_item(
    List<RemovedItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_removed_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_text_span(
    List<TextSpan> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_text_span(item, serializer);
    }
  }

  @protected
  void sse_encode_local_server_info(
    LocalServerInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.serverName, serializer);
    sse_encode_String(self.networkName, serializer);
  }

  @protected
  void sse_encode_member_view(MemberView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nick, serializer);
    sse_encode_opt_String(self.prefix, serializer);
    sse_encode_bool(self.away, serializer);
    sse_encode_String(self.sortKey, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_local_server_info(
    LocalServerInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_local_server_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_member_view(
    MemberView? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_member_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_proxy_config(
    ProxyConfig? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_proxy_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_proxy_config(ProxyConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
  }

  @protected
  void sse_encode_removed_item(RemovedItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.what, serializer);
    sse_encode_u_64(self.bytes, serializer);
  }

  @protected
  void sse_encode_server_config(ServerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.nickname, serializer);
    sse_encode_list_String(self.altNicks, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.realname, serializer);
    sse_encode_list_String(self.channels, serializer);
    sse_encode_opt_String(self.saslAccount, serializer);
    sse_encode_opt_String(self.saslPassword, serializer);
    sse_encode_opt_String(self.nickservPassword, serializer);
    sse_encode_opt_String(self.serverPassword, serializer);
    sse_encode_opt_box_autoadd_proxy_config(self.proxy, serializer);
  }

  @protected
  void sse_encode_span_style(SpanStyle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.bold, serializer);
    sse_encode_bool(self.italic, serializer);
    sse_encode_bool(self.underline, serializer);
    sse_encode_bool(self.strikethrough, serializer);
    sse_encode_bool(self.monospace, serializer);
    sse_encode_bool(self.inverse, serializer);
    sse_encode_opt_box_autoadd_u_8(self.fg, serializer);
    sse_encode_opt_box_autoadd_u_8(self.bg, serializer);
  }

  @protected
  void sse_encode_target(Target self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Target_Channel(name: final name):
        sse_encode_i_32(0, serializer);
        sse_encode_String(name, serializer);
      case Target_Direct(nick: final nick):
        sse_encode_i_32(1, serializer);
        sse_encode_String(nick, serializer);
    }
  }

  @protected
  void sse_encode_text_span(TextSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_span_style(self.style, serializer);
  }

  @protected
  void sse_encode_tor_status(TorStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ready, serializer);
    sse_encode_f_32(self.progress, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_opt_String(self.blocked, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
