// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -256085206;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__client__clean_media_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clean_media",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::client::clean_media(api_bytes))?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__connect_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "connect",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::api::types::ServerConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::connect(api_config)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__default_tls_port_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "default_tls_port",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::client::default_tls_port())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__client__disconnect_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "disconnect",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_reason = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::disconnect(api_id, api_reason)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__event_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "event_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::types::IrcEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::event_stream(api_id, api_sink)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__join_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "join",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_channel = <String>::sse_decode(&mut deserializer);
            let api_key = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::join(api_id, api_channel, api_key)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__server__local_server_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "local_server_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::server::local_server_info())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__server__local_server_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "local_server_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::server::local_server_start(api_data_dir)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__server__local_server_stop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "local_server_stop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::server::local_server_stop();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__part_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "part",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_channel = <String>::sse_decode(&mut deserializer);
            let api_reason = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::part(api_id, api_channel, api_reason)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__reconnect_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reconnect",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::reconnect(api_id)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__send_action_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_action",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_target = <String>::sse_decode(&mut deserializer);
            let api_text = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::send_action(api_id, api_target, api_text)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__send_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_target = <String>::sse_decode(&mut deserializer);
            let api_text = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::send_message(api_id, api_target, api_text)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__set_nick_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_nick",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_nick = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::set_nick(api_id, api_nick)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__set_topic_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_topic",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_id = <u64>::sse_decode(&mut deserializer);
            let api_channel = <String>::sse_decode(&mut deserializer);
            let api_topic = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::client::set_topic(api_id, api_channel, api_topic)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__tor__tor_port_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "tor_port",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>(crate::api::tor::tor_port())?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__client__tor_socks_port_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "tor_socks_port",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::client::tor_socks_port())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__tor__tor_start_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "tor_start",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data_dir = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::tor::tor_start(api_data_dir)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__tor__tor_status_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "tor_status_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::tor::TorStatus,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::tor::tor_status_stream(api_sink)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__tor__tor_stop_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "tor_stop",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::tor::tor_stop();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::types::IrcEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::tor::TorStatus, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::types::AuthOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::types::AuthOutcome::Sasl;
            }
            1 => {
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::types::AuthOutcome::NickServFallback { reason: var_reason };
            }
            2 => {
                return crate::api::types::AuthOutcome::Anonymous;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::types::ChatMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_target = <crate::api::types::Target>::sse_decode(deserializer);
        let mut var_sender = <String>::sse_decode(deserializer);
        let mut var_senderPrefix = <Option<String>>::sse_decode(deserializer);
        let mut var_spans = <Vec<crate::api::types::TextSpan>>::sse_decode(deserializer);
        let mut var_isSelf = <bool>::sse_decode(deserializer);
        let mut var_isMention = <bool>::sse_decode(deserializer);
        let mut var_isAction = <bool>::sse_decode(deserializer);
        let mut var_isNotice = <bool>::sse_decode(deserializer);
        return crate::api::types::ChatMessage {
            target: var_target,
            sender: var_sender,
            sender_prefix: var_senderPrefix,
            spans: var_spans,
            is_self: var_isSelf,
            is_mention: var_isMention,
            is_action: var_isAction,
            is_notice: var_isNotice,
        };
    }
}

impl SseDecode for crate::api::types::CleanOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_bytes = <Vec<u8>>::sse_decode(deserializer);
                let mut var_kind = <String>::sse_decode(deserializer);
                let mut var_removed =
                    <Vec<crate::api::types::RemovedItem>>::sse_decode(deserializer);
                return crate::api::types::CleanOutcome::Cleaned {
                    bytes: var_bytes,
                    kind: var_kind,
                    removed: var_removed,
                };
            }
            1 => {
                let mut var_kind = <String>::sse_decode(deserializer);
                return crate::api::types::CleanOutcome::AlreadyClean { kind: var_kind };
            }
            2 => {
                return crate::api::types::CleanOutcome::NotAnImage;
            }
            3 => {
                let mut var_detail = <String>::sse_decode(deserializer);
                return crate::api::types::CleanOutcome::Malformed { detail: var_detail };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::ConnectionStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::types::ConnectionStatus::Disconnected;
            }
            1 => {
                return crate::api::types::ConnectionStatus::Connecting;
            }
            2 => {
                return crate::api::types::ConnectionStatus::Registering;
            }
            3 => {
                return crate::api::types::ConnectionStatus::Connected;
            }
            4 => {
                let mut var_retryInSecs = <u64>::sse_decode(deserializer);
                let mut var_attempt = <u32>::sse_decode(deserializer);
                return crate::api::types::ConnectionStatus::Reconnecting {
                    retry_in_secs: var_retryInSecs,
                    attempt: var_attempt,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::types::IrcEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_status =
                    <crate::api::types::ConnectionStatus>::sse_decode(deserializer);
                let mut var_detail = <Option<String>>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Status {
                    status: var_status,
                    detail: var_detail,
                };
            }
            1 => {
                let mut var_nick = <String>::sse_decode(deserializer);
                let mut var_network = <Option<String>>::sse_decode(deserializer);
                let mut var_auth = <crate::api::types::AuthOutcome>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Registered {
                    nick: var_nick,
                    network: var_network,
                    auth: var_auth,
                };
            }
            2 => {
                let mut var_network = <String>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::NetworkNamed {
                    network: var_network,
                };
            }
            3 => {
                let mut var_message = <crate::api::types::ChatMessage>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Message {
                    message: var_message,
                };
            }
            4 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_nick = <String>::sse_decode(deserializer);
                let mut var_isSelf = <bool>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Joined {
                    channel: var_channel,
                    nick: var_nick,
                    is_self: var_isSelf,
                };
            }
            5 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_nick = <String>::sse_decode(deserializer);
                let mut var_isSelf = <bool>::sse_decode(deserializer);
                let mut var_reason = <Option<String>>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Parted {
                    channel: var_channel,
                    nick: var_nick,
                    is_self: var_isSelf,
                    reason: var_reason,
                };
            }
            6 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_nick = <String>::sse_decode(deserializer);
                let mut var_reason = <Option<String>>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Quit {
                    channel: var_channel,
                    nick: var_nick,
                    reason: var_reason,
                };
            }
            7 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_old = <String>::sse_decode(deserializer);
                let mut var_new_ = <String>::sse_decode(deserializer);
                let mut var_isSelf = <bool>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::NickChanged {
                    channel: var_channel,
                    old: var_old,
                    new: var_new_,
                    is_self: var_isSelf,
                };
            }
            8 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_topic = <String>::sse_decode(deserializer);
                let mut var_setBy = <Option<String>>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::TopicChanged {
                    channel: var_channel,
                    topic: var_topic,
                    set_by: var_setBy,
                };
            }
            9 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_members =
                    <Vec<crate::api::types::MemberView>>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::MemberList {
                    channel: var_channel,
                    members: var_members,
                };
            }
            10 => {
                let mut var_channel = <String>::sse_decode(deserializer);
                let mut var_by = <Option<String>>::sse_decode(deserializer);
                let mut var_affected = <Vec<String>>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::ModeChanged {
                    channel: var_channel,
                    by: var_by,
                    affected: var_affected,
                };
            }
            11 => {
                let mut var_channel = <Option<String>>::sse_decode(deserializer);
                let mut var_count = <u64>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::MessagesDropped {
                    channel: var_channel,
                    count: var_count,
                };
            }
            12 => {
                let mut var_message = <String>::sse_decode(deserializer);
                let mut var_fatal = <bool>::sse_decode(deserializer);
                return crate::api::types::IrcEvent::Error {
                    message: var_message,
                    fatal: var_fatal,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::MemberView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::MemberView>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::RemovedItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::RemovedItem>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::types::TextSpan> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::types::TextSpan>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::server::LocalServerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_port = <u16>::sse_decode(deserializer);
        let mut var_serverName = <String>::sse_decode(deserializer);
        let mut var_networkName = <String>::sse_decode(deserializer);
        return crate::api::server::LocalServerInfo {
            port: var_port,
            server_name: var_serverName,
            network_name: var_networkName,
        };
    }
}

impl SseDecode for crate::api::types::MemberView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_nick = <String>::sse_decode(deserializer);
        let mut var_prefix = <Option<String>>::sse_decode(deserializer);
        let mut var_away = <bool>::sse_decode(deserializer);
        return crate::api::types::MemberView {
            nick: var_nick,
            prefix: var_prefix,
            away: var_away,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::server::LocalServerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::server::LocalServerInfo>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::types::ProxyConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::types::ProxyConfig>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u16>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::types::ProxyConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_host = <String>::sse_decode(deserializer);
        let mut var_port = <u16>::sse_decode(deserializer);
        let mut var_username = <Option<String>>::sse_decode(deserializer);
        let mut var_password = <Option<String>>::sse_decode(deserializer);
        return crate::api::types::ProxyConfig {
            host: var_host,
            port: var_port,
            username: var_username,
            password: var_password,
        };
    }
}

impl SseDecode for crate::api::types::RemovedItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_what = <String>::sse_decode(deserializer);
        let mut var_bytes = <u64>::sse_decode(deserializer);
        return crate::api::types::RemovedItem {
            what: var_what,
            bytes: var_bytes,
        };
    }
}

impl SseDecode for crate::api::types::ServerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_host = <String>::sse_decode(deserializer);
        let mut var_port = <u16>::sse_decode(deserializer);
        let mut var_nickname = <String>::sse_decode(deserializer);
        let mut var_altNicks = <Vec<String>>::sse_decode(deserializer);
        let mut var_username = <Option<String>>::sse_decode(deserializer);
        let mut var_realname = <Option<String>>::sse_decode(deserializer);
        let mut var_channels = <Vec<String>>::sse_decode(deserializer);
        let mut var_saslAccount = <Option<String>>::sse_decode(deserializer);
        let mut var_saslPassword = <Option<String>>::sse_decode(deserializer);
        let mut var_nickservPassword = <Option<String>>::sse_decode(deserializer);
        let mut var_serverPassword = <Option<String>>::sse_decode(deserializer);
        let mut var_proxy = <Option<crate::api::types::ProxyConfig>>::sse_decode(deserializer);
        return crate::api::types::ServerConfig {
            host: var_host,
            port: var_port,
            nickname: var_nickname,
            alt_nicks: var_altNicks,
            username: var_username,
            realname: var_realname,
            channels: var_channels,
            sasl_account: var_saslAccount,
            sasl_password: var_saslPassword,
            nickserv_password: var_nickservPassword,
            server_password: var_serverPassword,
            proxy: var_proxy,
        };
    }
}

impl SseDecode for crate::api::types::SpanStyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_bold = <bool>::sse_decode(deserializer);
        let mut var_italic = <bool>::sse_decode(deserializer);
        let mut var_underline = <bool>::sse_decode(deserializer);
        let mut var_strikethrough = <bool>::sse_decode(deserializer);
        let mut var_monospace = <bool>::sse_decode(deserializer);
        let mut var_inverse = <bool>::sse_decode(deserializer);
        let mut var_fg = <Option<u8>>::sse_decode(deserializer);
        let mut var_bg = <Option<u8>>::sse_decode(deserializer);
        return crate::api::types::SpanStyle {
            bold: var_bold,
            italic: var_italic,
            underline: var_underline,
            strikethrough: var_strikethrough,
            monospace: var_monospace,
            inverse: var_inverse,
            fg: var_fg,
            bg: var_bg,
        };
    }
}

impl SseDecode for crate::api::types::Target {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_name = <String>::sse_decode(deserializer);
                return crate::api::types::Target::Channel { name: var_name };
            }
            1 => {
                let mut var_nick = <String>::sse_decode(deserializer);
                return crate::api::types::Target::Direct { nick: var_nick };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::types::TextSpan {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_text = <String>::sse_decode(deserializer);
        let mut var_style = <crate::api::types::SpanStyle>::sse_decode(deserializer);
        return crate::api::types::TextSpan {
            text: var_text,
            style: var_style,
        };
    }
}

impl SseDecode for crate::api::tor::TorStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ready = <bool>::sse_decode(deserializer);
        let mut var_progress = <f32>::sse_decode(deserializer);
        let mut var_summary = <String>::sse_decode(deserializer);
        let mut var_blocked = <Option<String>>::sse_decode(deserializer);
        return crate::api::tor::TorStatus {
            ready: var_ready,
            progress: var_progress,
            summary: var_summary,
            blocked: var_blocked,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__client__clean_media_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__client__connect_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__client__disconnect_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__client__event_stream_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__init_app_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__client__join_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__server__local_server_info_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__server__local_server_start_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__server__local_server_stop_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__client__part_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__client__reconnect_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__client__send_action_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__crate__api__client__send_message_impl(port, ptr, rust_vec_len, data_len),
        15 => wire__crate__api__client__set_nick_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__api__client__set_topic_impl(port, ptr, rust_vec_len, data_len),
        17 => wire__crate__api__tor__tor_port_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__api__tor__tor_start_impl(port, ptr, rust_vec_len, data_len),
        20 => wire__crate__api__tor__tor_status_stream_impl(port, ptr, rust_vec_len, data_len),
        21 => wire__crate__api__tor__tor_stop_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__client__default_tls_port_impl(ptr, rust_vec_len, data_len),
        18 => wire__crate__api__client__tor_socks_port_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::AuthOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::AuthOutcome::Sasl => [0.into_dart()].into_dart(),
            crate::api::types::AuthOutcome::NickServFallback { reason } => {
                [1.into_dart(), reason.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::AuthOutcome::Anonymous => [2.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::AuthOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::AuthOutcome>
    for crate::api::types::AuthOutcome
{
    fn into_into_dart(self) -> crate::api::types::AuthOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ChatMessage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.target.into_into_dart().into_dart(),
            self.sender.into_into_dart().into_dart(),
            self.sender_prefix.into_into_dart().into_dart(),
            self.spans.into_into_dart().into_dart(),
            self.is_self.into_into_dart().into_dart(),
            self.is_mention.into_into_dart().into_dart(),
            self.is_action.into_into_dart().into_dart(),
            self.is_notice.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ChatMessage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ChatMessage>
    for crate::api::types::ChatMessage
{
    fn into_into_dart(self) -> crate::api::types::ChatMessage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::CleanOutcome {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::CleanOutcome::Cleaned {
                bytes,
                kind,
                removed,
            } => [
                0.into_dart(),
                bytes.into_into_dart().into_dart(),
                kind.into_into_dart().into_dart(),
                removed.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::CleanOutcome::AlreadyClean { kind } => {
                [1.into_dart(), kind.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::CleanOutcome::NotAnImage => [2.into_dart()].into_dart(),
            crate::api::types::CleanOutcome::Malformed { detail } => {
                [3.into_dart(), detail.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::CleanOutcome
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::CleanOutcome>
    for crate::api::types::CleanOutcome
{
    fn into_into_dart(self) -> crate::api::types::CleanOutcome {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ConnectionStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::ConnectionStatus::Disconnected => [0.into_dart()].into_dart(),
            crate::api::types::ConnectionStatus::Connecting => [1.into_dart()].into_dart(),
            crate::api::types::ConnectionStatus::Registering => [2.into_dart()].into_dart(),
            crate::api::types::ConnectionStatus::Connected => [3.into_dart()].into_dart(),
            crate::api::types::ConnectionStatus::Reconnecting {
                retry_in_secs,
                attempt,
            } => [
                4.into_dart(),
                retry_in_secs.into_into_dart().into_dart(),
                attempt.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ConnectionStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ConnectionStatus>
    for crate::api::types::ConnectionStatus
{
    fn into_into_dart(self) -> crate::api::types::ConnectionStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::IrcEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::IrcEvent::Status { status, detail } => [
                0.into_dart(),
                status.into_into_dart().into_dart(),
                detail.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::Registered {
                nick,
                network,
                auth,
            } => [
                1.into_dart(),
                nick.into_into_dart().into_dart(),
                network.into_into_dart().into_dart(),
                auth.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::NetworkNamed { network } => {
                [2.into_dart(), network.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::IrcEvent::Message { message } => {
                [3.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::IrcEvent::Joined {
                channel,
                nick,
                is_self,
            } => [
                4.into_dart(),
                channel.into_into_dart().into_dart(),
                nick.into_into_dart().into_dart(),
                is_self.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::Parted {
                channel,
                nick,
                is_self,
                reason,
            } => [
                5.into_dart(),
                channel.into_into_dart().into_dart(),
                nick.into_into_dart().into_dart(),
                is_self.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::Quit {
                channel,
                nick,
                reason,
            } => [
                6.into_dart(),
                channel.into_into_dart().into_dart(),
                nick.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::NickChanged {
                channel,
                old,
                new,
                is_self,
            } => [
                7.into_dart(),
                channel.into_into_dart().into_dart(),
                old.into_into_dart().into_dart(),
                new.into_into_dart().into_dart(),
                is_self.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::TopicChanged {
                channel,
                topic,
                set_by,
            } => [
                8.into_dart(),
                channel.into_into_dart().into_dart(),
                topic.into_into_dart().into_dart(),
                set_by.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::MemberList { channel, members } => [
                9.into_dart(),
                channel.into_into_dart().into_dart(),
                members.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::ModeChanged {
                channel,
                by,
                affected,
            } => [
                10.into_dart(),
                channel.into_into_dart().into_dart(),
                by.into_into_dart().into_dart(),
                affected.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::MessagesDropped { channel, count } => [
                11.into_dart(),
                channel.into_into_dart().into_dart(),
                count.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::types::IrcEvent::Error { message, fatal } => [
                12.into_dart(),
                message.into_into_dart().into_dart(),
                fatal.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::IrcEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::IrcEvent>
    for crate::api::types::IrcEvent
{
    fn into_into_dart(self) -> crate::api::types::IrcEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::server::LocalServerInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.port.into_into_dart().into_dart(),
            self.server_name.into_into_dart().into_dart(),
            self.network_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::server::LocalServerInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::server::LocalServerInfo>
    for crate::api::server::LocalServerInfo
{
    fn into_into_dart(self) -> crate::api::server::LocalServerInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::MemberView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.nick.into_into_dart().into_dart(),
            self.prefix.into_into_dart().into_dart(),
            self.away.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::MemberView {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::MemberView>
    for crate::api::types::MemberView
{
    fn into_into_dart(self) -> crate::api::types::MemberView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ProxyConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.host.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ProxyConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ProxyConfig>
    for crate::api::types::ProxyConfig
{
    fn into_into_dart(self) -> crate::api::types::ProxyConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::RemovedItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.what.into_into_dart().into_dart(),
            self.bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::RemovedItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::RemovedItem>
    for crate::api::types::RemovedItem
{
    fn into_into_dart(self) -> crate::api::types::RemovedItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::ServerConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.host.into_into_dart().into_dart(),
            self.port.into_into_dart().into_dart(),
            self.nickname.into_into_dart().into_dart(),
            self.alt_nicks.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
            self.realname.into_into_dart().into_dart(),
            self.channels.into_into_dart().into_dart(),
            self.sasl_account.into_into_dart().into_dart(),
            self.sasl_password.into_into_dart().into_dart(),
            self.nickserv_password.into_into_dart().into_dart(),
            self.server_password.into_into_dart().into_dart(),
            self.proxy.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::types::ServerConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::ServerConfig>
    for crate::api::types::ServerConfig
{
    fn into_into_dart(self) -> crate::api::types::ServerConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::SpanStyle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.bold.into_into_dart().into_dart(),
            self.italic.into_into_dart().into_dart(),
            self.underline.into_into_dart().into_dart(),
            self.strikethrough.into_into_dart().into_dart(),
            self.monospace.into_into_dart().into_dart(),
            self.inverse.into_into_dart().into_dart(),
            self.fg.into_into_dart().into_dart(),
            self.bg.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::SpanStyle {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::SpanStyle>
    for crate::api::types::SpanStyle
{
    fn into_into_dart(self) -> crate::api::types::SpanStyle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::Target {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::types::Target::Channel { name } => {
                [0.into_dart(), name.into_into_dart().into_dart()].into_dart()
            }
            crate::api::types::Target::Direct { nick } => {
                [1.into_dart(), nick.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::Target {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::Target> for crate::api::types::Target {
    fn into_into_dart(self) -> crate::api::types::Target {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::types::TextSpan {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.text.into_into_dart().into_dart(),
            self.style.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::types::TextSpan {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::types::TextSpan>
    for crate::api::types::TextSpan
{
    fn into_into_dart(self) -> crate::api::types::TextSpan {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::tor::TorStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ready.into_into_dart().into_dart(),
            self.progress.into_into_dart().into_dart(),
            self.summary.into_into_dart().into_dart(),
            self.blocked.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::tor::TorStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::tor::TorStatus> for crate::api::tor::TorStatus {
    fn into_into_dart(self) -> crate::api::tor::TorStatus {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::types::IrcEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<crate::api::tor::TorStatus, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::types::AuthOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::AuthOutcome::Sasl => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::types::AuthOutcome::NickServFallback { reason } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::types::AuthOutcome::Anonymous => {
                <i32>::sse_encode(2, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::types::ChatMessage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::types::Target>::sse_encode(self.target, serializer);
        <String>::sse_encode(self.sender, serializer);
        <Option<String>>::sse_encode(self.sender_prefix, serializer);
        <Vec<crate::api::types::TextSpan>>::sse_encode(self.spans, serializer);
        <bool>::sse_encode(self.is_self, serializer);
        <bool>::sse_encode(self.is_mention, serializer);
        <bool>::sse_encode(self.is_action, serializer);
        <bool>::sse_encode(self.is_notice, serializer);
    }
}

impl SseEncode for crate::api::types::CleanOutcome {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::CleanOutcome::Cleaned {
                bytes,
                kind,
                removed,
            } => {
                <i32>::sse_encode(0, serializer);
                <Vec<u8>>::sse_encode(bytes, serializer);
                <String>::sse_encode(kind, serializer);
                <Vec<crate::api::types::RemovedItem>>::sse_encode(removed, serializer);
            }
            crate::api::types::CleanOutcome::AlreadyClean { kind } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(kind, serializer);
            }
            crate::api::types::CleanOutcome::NotAnImage => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::types::CleanOutcome::Malformed { detail } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(detail, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::ConnectionStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::ConnectionStatus::Disconnected => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::types::ConnectionStatus::Connecting => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::types::ConnectionStatus::Registering => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::types::ConnectionStatus::Connected => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::types::ConnectionStatus::Reconnecting {
                retry_in_secs,
                attempt,
            } => {
                <i32>::sse_encode(4, serializer);
                <u64>::sse_encode(retry_in_secs, serializer);
                <u32>::sse_encode(attempt, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::types::IrcEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::IrcEvent::Status { status, detail } => {
                <i32>::sse_encode(0, serializer);
                <crate::api::types::ConnectionStatus>::sse_encode(status, serializer);
                <Option<String>>::sse_encode(detail, serializer);
            }
            crate::api::types::IrcEvent::Registered {
                nick,
                network,
                auth,
            } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(nick, serializer);
                <Option<String>>::sse_encode(network, serializer);
                <crate::api::types::AuthOutcome>::sse_encode(auth, serializer);
            }
            crate::api::types::IrcEvent::NetworkNamed { network } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(network, serializer);
            }
            crate::api::types::IrcEvent::Message { message } => {
                <i32>::sse_encode(3, serializer);
                <crate::api::types::ChatMessage>::sse_encode(message, serializer);
            }
            crate::api::types::IrcEvent::Joined {
                channel,
                nick,
                is_self,
            } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(channel, serializer);
                <String>::sse_encode(nick, serializer);
                <bool>::sse_encode(is_self, serializer);
            }
            crate::api::types::IrcEvent::Parted {
                channel,
                nick,
                is_self,
                reason,
            } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(channel, serializer);
                <String>::sse_encode(nick, serializer);
                <bool>::sse_encode(is_self, serializer);
                <Option<String>>::sse_encode(reason, serializer);
            }
            crate::api::types::IrcEvent::Quit {
                channel,
                nick,
                reason,
            } => {
                <i32>::sse_encode(6, serializer);
                <String>::sse_encode(channel, serializer);
                <String>::sse_encode(nick, serializer);
                <Option<String>>::sse_encode(reason, serializer);
            }
            crate::api::types::IrcEvent::NickChanged {
                channel,
                old,
                new,
                is_self,
            } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(channel, serializer);
                <String>::sse_encode(old, serializer);
                <String>::sse_encode(new, serializer);
                <bool>::sse_encode(is_self, serializer);
            }
            crate::api::types::IrcEvent::TopicChanged {
                channel,
                topic,
                set_by,
            } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(channel, serializer);
                <String>::sse_encode(topic, serializer);
                <Option<String>>::sse_encode(set_by, serializer);
            }
            crate::api::types::IrcEvent::MemberList { channel, members } => {
                <i32>::sse_encode(9, serializer);
                <String>::sse_encode(channel, serializer);
                <Vec<crate::api::types::MemberView>>::sse_encode(members, serializer);
            }
            crate::api::types::IrcEvent::ModeChanged {
                channel,
                by,
                affected,
            } => {
                <i32>::sse_encode(10, serializer);
                <String>::sse_encode(channel, serializer);
                <Option<String>>::sse_encode(by, serializer);
                <Vec<String>>::sse_encode(affected, serializer);
            }
            crate::api::types::IrcEvent::MessagesDropped { channel, count } => {
                <i32>::sse_encode(11, serializer);
                <Option<String>>::sse_encode(channel, serializer);
                <u64>::sse_encode(count, serializer);
            }
            crate::api::types::IrcEvent::Error { message, fatal } => {
                <i32>::sse_encode(12, serializer);
                <String>::sse_encode(message, serializer);
                <bool>::sse_encode(fatal, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::MemberView> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::MemberView>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::RemovedItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::RemovedItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::types::TextSpan> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::types::TextSpan>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::server::LocalServerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u16>::sse_encode(self.port, serializer);
        <String>::sse_encode(self.server_name, serializer);
        <String>::sse_encode(self.network_name, serializer);
    }
}

impl SseEncode for crate::api::types::MemberView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.nick, serializer);
        <Option<String>>::sse_encode(self.prefix, serializer);
        <bool>::sse_encode(self.away, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::server::LocalServerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::server::LocalServerInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::types::ProxyConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::types::ProxyConfig>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u16>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::types::ProxyConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.host, serializer);
        <u16>::sse_encode(self.port, serializer);
        <Option<String>>::sse_encode(self.username, serializer);
        <Option<String>>::sse_encode(self.password, serializer);
    }
}

impl SseEncode for crate::api::types::RemovedItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.what, serializer);
        <u64>::sse_encode(self.bytes, serializer);
    }
}

impl SseEncode for crate::api::types::ServerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.host, serializer);
        <u16>::sse_encode(self.port, serializer);
        <String>::sse_encode(self.nickname, serializer);
        <Vec<String>>::sse_encode(self.alt_nicks, serializer);
        <Option<String>>::sse_encode(self.username, serializer);
        <Option<String>>::sse_encode(self.realname, serializer);
        <Vec<String>>::sse_encode(self.channels, serializer);
        <Option<String>>::sse_encode(self.sasl_account, serializer);
        <Option<String>>::sse_encode(self.sasl_password, serializer);
        <Option<String>>::sse_encode(self.nickserv_password, serializer);
        <Option<String>>::sse_encode(self.server_password, serializer);
        <Option<crate::api::types::ProxyConfig>>::sse_encode(self.proxy, serializer);
    }
}

impl SseEncode for crate::api::types::SpanStyle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.bold, serializer);
        <bool>::sse_encode(self.italic, serializer);
        <bool>::sse_encode(self.underline, serializer);
        <bool>::sse_encode(self.strikethrough, serializer);
        <bool>::sse_encode(self.monospace, serializer);
        <bool>::sse_encode(self.inverse, serializer);
        <Option<u8>>::sse_encode(self.fg, serializer);
        <Option<u8>>::sse_encode(self.bg, serializer);
    }
}

impl SseEncode for crate::api::types::Target {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::types::Target::Channel { name } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(name, serializer);
            }
            crate::api::types::Target::Direct { nick } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(nick, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::types::TextSpan {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.text, serializer);
        <crate::api::types::SpanStyle>::sse_encode(self.style, serializer);
    }
}

impl SseEncode for crate::api::tor::TorStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ready, serializer);
        <f32>::sse_encode(self.progress, serializer);
        <String>::sse_encode(self.summary, serializer);
        <Option<String>>::sse_encode(self.blocked, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
