#!/bin/sh
# Write down what `make dev-server` just started, as dev/server.txt.
#
# None of it is guessable. Ergo generates its certificate on first start, so
# the fingerprint and the expiry differ on every checkout, and the file is the
# only place they are written down in one piece.
#
# A stale copy would be worse than none, so `make dev-server-stop` and
# `make dev-server-clean` both delete it again.

set -eu

cert=dev/ergo/fullchain.pem
out=dev/server.txt

# openssl is not on every machine, and the rest of the file is still worth
# writing without it.
cert_field() {
    if [ -f "$cert" ] && command -v openssl >/dev/null 2>&1; then
        openssl x509 -in "$cert" -noout "$@" 2>/dev/null | cut -d= -f2- ||
            echo "(unreadable)"
    elif [ -f "$cert" ]; then
        echo "(openssl not on PATH)"
    else
        echo "(not generated yet)"
    fi
}

status=$(docker ps --filter name=ddirc-dev-ircd --format '{{.Status}}' \
    2>/dev/null || true)
[ -n "$status" ] || status="(not running)"

cat >"$out" <<EOF
ddIRC dev server
================

Generated by 'make dev-server' on $(date). Rewritten on every start and
deleted on stop, so if this file exists the server was last seen running.

  CONNECT TO     localhost:6697        or 127.0.0.1:6697, either works.
                                       TLS only, loopback only.

  Network name   ErgoTest              what it calls its network
  Server name    ergo.test             what it calls ITSELF. This is not a
                                       DNS name and never resolves - typing
                                       it as the host is a DNS error.
  Container      ddirc-dev-ircd        $status

  Certificate    $cert
  Fingerprint    $(cert_field -fingerprint -sha1)
  Expires        $(cert_field -enddate)

The certificate is self-signed, so ddIRC itself will NOT connect to this
without the certificate being trusted by the operating system first. That is
deliberate: the client has no option to skip verification. The Rust tests do
connect, by adding this one certificate as a trusted root for that connection
alone.

  make test-integration   the end-to-end suite, against this server
  make dev-server-logs    follow its log
  make dev-server-stop    stop it, keeping accounts and certificates
  make dev-server-clean   stop it and throw dev/ergo/ away

Check it answers, without involving the app at all:

  printf 'NICK probe\r\nUSER probe 0 * :probe\r\nQUIT :bye\r\n' \\
    | openssl s_client -connect 127.0.0.1:6697 \\
        -servername localhost -CAfile $cert -quiet

Register an account, for testing SASL (the '*' skips e-mail verification):

  REGISTER <account> * <password>

dev/README.md has the rest: pointing the app at it, using another IRC client,
and what to do when it will not start.
EOF
