// Rasterise the app icon, from lib/src/ui/mark_spec.dart.
//
//     make icons        (or: dart run tool/make_icons.dart)
//
// Run it after changing MarkSpec, and commit what it writes. The output is
// deterministic: the same spec produces byte-identical files, so a run that
// changes nothing shows up as nothing in `git status`.
//
// Why a generator and not a drawing program: the mark is four strokes on a
// rounded square, and it has to exist at eleven sizes across three platforms.
// Exporting those by hand is eleven chances to ship a stale one, and the
// smallest — 16 pixels, the Windows taskbar — is the one a general-purpose
// export pipeline does worst, because it downscales a large bitmap instead of
// drawing the shape at the size it will be seen.
//
// Everything here is drawn from signed distance fields and antialiased by
// coverage, which is why 16px comes out crisp. No image library is involved:
// PNG is a zlib stream of filtered scanlines, and ICO is a directory of PNGs,
// both of which are shorter to write than to depend on.
//
// Plain Dart, not Flutter — `dart:ui` would give us a Canvas but only inside a
// running engine, which is a poor trade for a build-time script.

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:ddirc/src/ui/mark_spec.dart';

/// Windows wants every size in one file. 16 and 32 are the taskbar and the
/// title bar, 256 is the one Explorer shows in a large-icon view.
const _icoSizes = [16, 24, 32, 48, 64, 128, 256];

/// The notification area, at the four display scalings Windows offers: 16
/// pixels at 100%, then 125%, 150% and 200%. Windows picks from the file
/// rather than scaling, so an omitted size is a blurred icon, not a missing
/// one — which is the kind of fault nobody reports.
const _trayIcoSizes = [16, 20, 24, 32];

/// How much of a menu-bar template the glyph occupies.
///
/// The macOS tray image is the hash alone, with no field behind it, so it has
/// to be drawn larger than it is inside the app icon or it reads as a speck in
/// a 22-point slot. Derived from [MarkSpec.inset] rather than typed as a
/// number, so widening the glyph in the spec cannot silently shrink this.
const _templateScale = 0.86 / (1 - 2 * MarkSpec.inset);

/// Android's five densities, at 48dp for the legacy icon and 108dp for the
/// adaptive one.
const _androidDensities = {
  'mdpi': 1,
  'hdpi': 2, // 1.5, rounded up to keep every size an integer
  'xhdpi': 2,
  'xxhdpi': 3,
  'xxxhdpi': 4,
};

/// How much of a macOS icon's canvas the mark occupies.
///
/// Apple's grid puts a rounded-rectangle app icon at about four fifths of the
/// canvas, with the rest transparent margin, and the Dock lines every icon up
/// on that assumption. Full bleed would simply look bigger than its
/// neighbours.
const _macScale = 0.82;

/// How much of the adaptive foreground the mark occupies.
///
/// Android masks that canvas to whatever shape the launcher uses and can
/// animate it, so only the middle two thirds is guaranteed to survive. At this
/// scale the hash spans just under half the canvas — comfortably inside the
/// safe zone, and still the size of a normal launcher icon once masked.
const _foregroundScale = 0.80;

void main(List<String> args) {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('run this from the repository root');
    exit(2);
  }

  final written = <String, int>{};

  void write(String path, List<int> bytes) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsBytesSync(bytes);
    written[path] = bytes.length;
  }

  // Windows: one .ico holding every size, drawn at each.
  write(
    'windows/runner/resources/app_icon.ico',
    ico([for (final size in _icoSizes) png(render(size), size, size)]),
  );

  // Android: the legacy launcher icon, and the adaptive one's foreground.
  for (final MapEntry(key: density, value: factor)
      in _androidDensities.entries) {
    final dir = 'android/app/src/main/res/mipmap-$density';
    final legacy = 48 * factor;
    final adaptive = 108 * factor;
    write('$dir/ic_launcher.png', png(render(legacy), legacy, legacy));
    write(
      '$dir/ic_launcher_foreground.png',
      png(
        render(adaptive, field: false, scale: _foregroundScale),
        adaptive,
        adaptive,
      ),
    );
  }

  // The adaptive icon itself: a flat field, and the glyph floating above it.
  // Generated rather than hand-written so the colour cannot drift from the
  // one the bitmaps are drawn in.
  write(
    'android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml',
    utf8.encode(
      '<?xml version="1.0" encoding="utf-8"?>\n'
      '<!-- Generated by tool/make_icons.dart. Do not edit. -->\n'
      '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
      '    <background android:drawable="@color/ic_launcher_background" />\n'
      '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
      '</adaptive-icon>\n',
    ),
  );
  write(
    'android/app/src/main/res/values/ic_launcher_background.xml',
    utf8.encode(
      '<?xml version="1.0" encoding="utf-8"?>\n'
      '<!-- Generated by tool/make_icons.dart. Do not edit. -->\n'
      '<resources>\n'
      '    <color name="ic_launcher_background">#${_hex(MarkSpec.fieldColor)}</color>\n'
      '</resources>\n',
    ),
  );

  // macOS and iOS: the sizes are whatever the generated asset catalogue asks
  // for, read back out of it rather than listed again here.
  //
  // The two want opposite things. macOS shows the icon as drawn, so it keeps
  // the rounded corners and sits inside Apple's margin. iOS masks the corners
  // itself and rejects any transparency at all, so its icons are square, edge
  // to edge, and written without an alpha channel.
  appleIcons('macos/Runner/Assets.xcassets/AppIcon.appiconset', write, macIcon);
  appleIcons('ios/Runner/Assets.xcassets/AppIcon.appiconset', write, iosIcon);

  // The tray. Bundled as a Flutter asset rather than a platform resource,
  // because tray_manager is handed a path at runtime and resolves it out of
  // the asset bundle.
  //
  // Windows and Linux get the mark as it appears everywhere else — the tray
  // icon sits beside the taskbar button and should be the same thing. macOS
  // gets a template instead: the menu bar recolours what it is given, so an
  // image that is not black-on-transparent comes out as a smudge on a dark
  // menu bar and a different smudge on a light one.
  write(
    'assets/tray/tray.ico',
    ico([for (final size in _trayIcoSizes) png(render(size), size, size)]),
  );
  write('assets/tray/tray.png', png(render(64), 64, 64));
  write('assets/tray/tray_template.png', trayTemplate(44));

  // For anywhere outside a build: a readme, a store listing, the platforms
  // that do not have a runner yet. The SVG is the one to hand to a designer.
  write('assets/icon/ddirc.png', png(render(512), 512, 512));
  write('assets/icon/ddirc.svg', utf8.encode(svg()));

  final names = written.keys.toList()..sort();
  for (final name in names) {
    stdout.writeln('  ${written[name]!.toString().padLeft(7)}  $name');
  }
  stdout.writeln('${written.length} files');
}

/// The macOS menu-bar image: the hash alone, in black, on transparency.
///
/// Marked as a template when it is handed to the tray, which is what lets the
/// system invert it for a dark menu bar and dim it when the bar is inactive.
/// A template's colour is discarded and only its alpha is read, so black here
/// is a convention rather than a choice of ink.
Uint8List trayTemplate(int size) => png(
  render(size, field: false, scale: _templateScale, glyph: 0xFF000000),
  size,
  size,
);

/// One macOS icon: rounded, inside Apple's margin, alpha kept.
Uint8List macIcon(int size) => png(render(size, scale: _macScale), size, size);

/// One iOS icon: square, edge to edge, and with no alpha channel at all.
Uint8List iosIcon(int size) => png(
  render(size, field: false, backdrop: MarkSpec.fieldColor),
  size,
  size,
  opaque: true,
);

/// Fill in an Xcode asset catalogue, at whatever sizes it asks for.
///
/// The catalogue is generated by `flutter create` and is the authority on which
/// files an Xcode build expects; restating that list here would be a second
/// copy to keep in step, and a missing icon in an asset catalogue is a build
/// warning that is easy to miss.
void appleIcons(
  String dir,
  void Function(String path, List<int> bytes) write,
  Uint8List Function(int size) draw,
) {
  final catalogue =
      jsonDecode(File('$dir/Contents.json').readAsStringSync())
          as Map<String, dynamic>;

  final wanted = <String, int>{};
  for (final entry
      in (catalogue['images'] as List).cast<Map<String, dynamic>>()) {
    final name = entry['filename'] as String?;
    if (name == null) continue;
    // "83.5x83.5" at "2x" is a 167-pixel file. The same file often appears
    // twice — 32 pixels is both 16pt@2x and 32pt@1x — hence a map.
    final points = double.parse((entry['size'] as String).split('x').first);
    final scale = int.parse((entry['scale'] as String).replaceAll('x', ''));
    wanted[name] = (points * scale).round();
  }

  for (final MapEntry(key: name, value: size) in wanted.entries) {
    write('$dir/$name', draw(size));
  }
}

String _hex(int argb) =>
    argb.toRadixString(16).padLeft(8, '0').substring(2).toUpperCase();

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------

/// The mark at [size] pixels square, as straight-alpha RGBA.
///
/// [field] draws the rounded square; without it only the glyph is drawn, on
/// transparency, which is what Android's adaptive foreground wants.
/// [scale] is how much of the canvas the mark occupies, centred.
/// [backdrop] fills the canvas edge to edge first, for iOS, which masks the
/// corners itself and will not accept an icon with any transparency in it.
/// [glyph] overrides the hash's colour, for the macOS menu-bar template, which
/// has to be a single opaque ink on transparency rather than the mark's own
/// near-white.
Uint8List render(
  int size, {
  bool field = true,
  double scale = 1,
  int? backdrop,
  int? glyph,
}) {
  final pixels = Uint8List(size * size * 4);
  final side = size * scale;
  final origin = (size - side) / 2;

  // Unit coordinates to pixels, at the centre of pixel (x, y).
  double px(double u) => origin + u * side;

  final radius = MarkSpec.corner * side;
  final half = side / 2;
  final centre = origin + half;
  final ink = MarkSpec.stroke * side / 2;

  for (var y = 0; y < size; y++) {
    for (var x = 0; x < size; x++) {
      final cx = x + 0.5;
      final cy = y + 0.5;

      var r = 0.0, g = 0.0, b = 0.0, a = 0.0;

      if (backdrop != null) {
        (r, g, b, a) = _over(backdrop, 1, r, g, b, a);
      }

      if (field) {
        final cover = _coverage(
          _roundedBox(cx - centre, cy - centre, half, half, radius),
        );
        (r, g, b, a) = _over(MarkSpec.fieldColor, cover, r, g, b, a);
      }

      // One distance for the whole glyph, so the four strokes do not blend
      // over one another where they cross.
      var d = double.infinity;
      for (final (x1, y1, x2, y2) in MarkSpec.strokes) {
        final ds = _segment(cx, cy, px(x1), px(y1), px(x2), px(y2), ink);
        if (ds < d) d = ds;
      }
      (r, g, b, a) = _over(
        glyph ?? MarkSpec.glyphColor,
        _coverage(d),
        r,
        g,
        b,
        a,
      );

      final i = (y * size + x) * 4;
      pixels[i] = (r * 255).round();
      pixels[i + 1] = (g * 255).round();
      pixels[i + 2] = (b * 255).round();
      pixels[i + 3] = (a * 255).round();
    }
  }
  return pixels;
}

/// A distance in pixels to how much of this pixel the shape covers.
///
/// The one-pixel ramp either side of the edge is the whole of the
/// antialiasing, and it is why the 16px icon is legible.
double _coverage(double distance) => (0.5 - distance).clamp(0.0, 1.0);

/// Signed distance to a rounded box centred on the origin.
double _roundedBox(double px, double py, double halfW, double halfH, double r) {
  final qx = px.abs() - halfW + r;
  final qy = py.abs() - halfH + r;
  final outside = math.sqrt(
    math.max(qx, 0) * math.max(qx, 0) + math.max(qy, 0) * math.max(qy, 0),
  );
  return math.min(math.max(qx, qy), 0) + outside - r;
}

/// Signed distance to a line from (ax, ay) to (bx, by), thickened by [r].
double _segment(
  double px,
  double py,
  double ax,
  double ay,
  double bx,
  double by,
  double r,
) {
  final pax = px - ax, pay = py - ay;
  final bax = bx - ax, bay = by - ay;
  final len = bax * bax + bay * bay;
  final h = len == 0 ? 0.0 : ((pax * bax + pay * bay) / len).clamp(0.0, 1.0);
  final dx = pax - bax * h, dy = pay - bay * h;
  return math.sqrt(dx * dx + dy * dy) - r;
}

/// Source-over compositing, in straight alpha.
(double, double, double, double) _over(
  int color,
  double alpha,
  double dr,
  double dg,
  double db,
  double da,
) {
  if (alpha <= 0) return (dr, dg, db, da);
  final sr = ((color >> 16) & 0xFF) / 255;
  final sg = ((color >> 8) & 0xFF) / 255;
  final sb = (color & 0xFF) / 255;
  final out = alpha + da * (1 - alpha);
  if (out <= 0) return (0, 0, 0, 0);
  double blend(double s, double d) => (s * alpha + d * da * (1 - alpha)) / out;
  return (blend(sr, dr), blend(sg, dg), blend(sb, db), out);
}

/// The same four strokes, as a vector file.
String svg() {
  final w = MarkSpec.stroke * 1000;
  final lines = [
    for (final (x1, y1, x2, y2) in MarkSpec.strokes)
      '  <line x1="${x1 * 1000}" y1="${y1 * 1000}" '
          'x2="${x2 * 1000}" y2="${y2 * 1000}" />',
  ].join('\n');

  return '<?xml version="1.0" encoding="UTF-8"?>\n'
      '<!-- Generated by tool/make_icons.dart from lib/src/ui/mark_spec.dart. -->\n'
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" '
      'width="1000" height="1000">\n'
      '  <rect width="1000" height="1000" rx="${MarkSpec.corner * 1000}" '
      'fill="#${_hex(MarkSpec.fieldColor)}" />\n'
      '  <g stroke="#${_hex(MarkSpec.glyphColor)}" stroke-width="$w" '
      'stroke-linecap="round">\n'
      '$lines\n'
      '  </g>\n'
      '</svg>\n';
}

// ---------------------------------------------------------------------------
// Containers
// ---------------------------------------------------------------------------

/// An 8-bit PNG. [pixels] must be `width * height * 4` bytes of straight-alpha
/// RGBA; [opaque] drops the alpha channel, which is what the App Store demands
/// of an iOS icon and what Xcode warns about if you skip.
Uint8List png(Uint8List pixels, int width, int height, {bool opaque = false}) {
  // Every scanline gets filter type 0 (none). Filtering would compress a
  // photograph better; this is flat colour, which zlib already handles.
  final channels = opaque ? 3 : 4;
  final stride = width * channels;
  final raw = Uint8List(height * (stride + 1));
  for (var y = 0; y < height; y++) {
    var at = y * (stride + 1);
    raw[at++] = 0;
    for (var x = 0; x < width; x++) {
      final from = (y * width + x) * 4;
      raw[at++] = pixels[from];
      raw[at++] = pixels[from + 1];
      raw[at++] = pixels[from + 2];
      if (!opaque) raw[at++] = pixels[from + 3];
    }
  }

  final header = BytesBuilder()
    ..add(_be32(width))
    ..add(_be32(height))
    ..addByte(8) // bits per channel
    ..addByte(opaque ? 2 : 6) // colour type: RGB or RGBA
    ..addByte(0) // deflate
    ..addByte(0) // adaptive filtering
    ..addByte(0); // no interlace

  final file = BytesBuilder()
    ..add(const [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
    ..add(_chunk('IHDR', header.toBytes()))
    ..add(_chunk('IDAT', ZLibEncoder(level: 9).convert(raw)))
    ..add(_chunk('IEND', const []));
  return file.toBytes();
}

/// An .ico wrapping already-encoded PNGs, largest last.
///
/// PNG-compressed entries rather than the old BMP ones: every Windows since
/// Vista reads them, and a 256px BMP entry alone would be 256 KB.
Uint8List ico(List<Uint8List> images) {
  final out = BytesBuilder()
    ..add(_le16(0)) // reserved
    ..add(_le16(1)) // type: icon
    ..add(_le16(images.length));

  var offset = 6 + images.length * 16;
  for (final image in images) {
    // The size comes back out of the PNG header rather than being passed in,
    // so the directory cannot end up describing a different image.
    final width = _readBe32(image, 16);
    out
      ..addByte(width >= 256 ? 0 : width) // 0 means 256
      ..addByte(width >= 256 ? 0 : width)
      ..addByte(0) // not a palette
      ..addByte(0) // reserved
      ..add(_le16(1)) // colour planes
      ..add(_le16(32)) // bits per pixel
      ..add(_le32(image.length))
      ..add(_le32(offset));
    offset += image.length;
  }
  for (final image in images) {
    out.add(image);
  }
  return out.toBytes();
}

List<int> _chunk(String type, List<int> data) {
  final body = BytesBuilder()
    ..add(ascii.encode(type))
    ..add(data);
  final bytes = body.toBytes();
  return [..._be32(data.length), ...bytes, ..._be32(_crc32(bytes))];
}

List<int> _be32(int v) => [
  (v >> 24) & 0xFF,
  (v >> 16) & 0xFF,
  (v >> 8) & 0xFF,
  v & 0xFF,
];

List<int> _le16(int v) => [v & 0xFF, (v >> 8) & 0xFF];

List<int> _le32(int v) => [
  v & 0xFF,
  (v >> 8) & 0xFF,
  (v >> 16) & 0xFF,
  (v >> 24) & 0xFF,
];

int _readBe32(List<int> bytes, int at) =>
    (bytes[at] << 24) |
    (bytes[at + 1] << 16) |
    (bytes[at + 2] << 8) |
    bytes[at + 3];

final _crcTable = List<int>.generate(256, (n) {
  var c = n;
  for (var k = 0; k < 8; k++) {
    c = (c & 1) != 0 ? 0xEDB88320 ^ (c >> 1) : c >> 1;
  }
  return c;
});

int _crc32(List<int> bytes) {
  var c = 0xFFFFFFFF;
  for (final byte in bytes) {
    c = _crcTable[(c ^ byte) & 0xFF] ^ (c >> 8);
  }
  return c ^ 0xFFFFFFFF;
}
