// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `connections`, `runtime`, `send`, `with_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Connection`

/// Open a connection and return its id.
///
/// The configuration is validated up front, so a bad host, a plaintext port, or
/// half-supplied SASL credentials fail here with a clear message rather than as
/// an opaque error later.
Future<BigInt> connect({required ServerConfig config}) =>
    RustLib.instance.api.crateApiClientConnect(config: config);

/// Subscribe to a connection's events. In Dart this returns a `Stream`.
///
/// Only one subscription per connection is possible; the UI should fan out from
/// the single stream rather than subscribing twice.
Stream<IrcEvent> eventStream({required BigInt id}) =>
    RustLib.instance.api.crateApiClientEventStream(id: id);

Future<void> join({required BigInt id, required String channel, String? key}) =>
    RustLib.instance.api.crateApiClientJoin(id: id, channel: channel, key: key);

Future<void> part_({
  required BigInt id,
  required String channel,
  String? reason,
}) => RustLib.instance.api.crateApiClientPart(
  id: id,
  channel: channel,
  reason: reason,
);

Future<void> sendMessage({
  required BigInt id,
  required String target,
  required String text,
}) => RustLib.instance.api.crateApiClientSendMessage(
  id: id,
  target: target,
  text: text,
);

Future<void> sendAction({
  required BigInt id,
  required String target,
  required String text,
}) => RustLib.instance.api.crateApiClientSendAction(
  id: id,
  target: target,
  text: text,
);

Future<void> setNick({required BigInt id, required String nick}) =>
    RustLib.instance.api.crateApiClientSetNick(id: id, nick: nick);

/// Set a channel topic. An empty string clears it.
Future<void> setTopic({
  required BigInt id,
  required String channel,
  required String topic,
}) => RustLib.instance.api.crateApiClientSetTopic(
  id: id,
  channel: channel,
  topic: topic,
);

/// Disconnect and release the connection.
///
/// Idempotent: disconnecting an unknown or already-closed connection succeeds,
/// so the UI does not have to track whether teardown already happened.
Future<void> disconnect({required BigInt id, String? reason}) =>
    RustLib.instance.api.crateApiClientDisconnect(id: id, reason: reason);

/// The default port for IRC over TLS, so Dart does not hardcode it.
int defaultTlsPort() => RustLib.instance.api.crateApiClientDefaultTlsPort();
