// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `connections`, `dev_root_cert`, `runtime`, `send`, `with_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Connection`

/// Open a connection and return its id.
///
/// The configuration is validated up front, so a bad host, a plaintext port, or
/// half-supplied SASL credentials fail here with a clear message rather than as
/// an opaque error later.
Future<BigInt> connect({required ServerConfig config}) =>
    RustLib.instance.api.crateApiClientConnect(config: config);

/// Subscribe to a connection's events. In Dart this returns a `Stream`.
///
/// Only one subscription per connection is possible; the UI should fan out from
/// the single stream rather than subscribing twice.
Stream<IrcEvent> eventStream({required BigInt id}) =>
    RustLib.instance.api.crateApiClientEventStream(id: id);

Future<void> join({required BigInt id, required String channel, String? key}) =>
    RustLib.instance.api.crateApiClientJoin(id: id, channel: channel, key: key);

Future<void> part_({
  required BigInt id,
  required String channel,
  String? reason,
}) => RustLib.instance.api.crateApiClientPart(
  id: id,
  channel: channel,
  reason: reason,
);

Future<void> sendMessage({
  required BigInt id,
  required String target,
  required String text,
}) => RustLib.instance.api.crateApiClientSendMessage(
  id: id,
  target: target,
  text: text,
);

Future<void> sendAction({
  required BigInt id,
  required String target,
  required String text,
}) => RustLib.instance.api.crateApiClientSendAction(
  id: id,
  target: target,
  text: text,
);

Future<void> setNick({required BigInt id, required String nick}) =>
    RustLib.instance.api.crateApiClientSetNick(id: id, nick: nick);

/// Set a channel topic. An empty string clears it.
Future<void> setTopic({
  required BigInt id,
  required String channel,
  required String topic,
}) => RustLib.instance.api.crateApiClientSetTopic(
  id: id,
  channel: channel,
  topic: topic,
);

/// Offer a file to someone, over DCC.
///
/// `path` is read by the core, so the bytes never cross this boundary: a file
/// is streamed from disk to the socket, and a large one costs no more memory
/// than a small one.
///
/// Fails immediately, as a `FileTransferEnded` event carrying a reason, if a
/// proxy is configured — a normal DCC offer names the address the proxy exists
/// to hide, and there is no safe way to make one from behind Tor. See
/// `dcc::transfer`.
Future<void> sendFile({
  required BigInt id,
  required String target,
  required String path,
}) => RustLib.instance.api.crateApiClientSendFile(
  id: id,
  target: target,
  path: path,
);

/// Take up an offer, saving it into `directory`.
///
/// `transfer_id` is the id the offer arrived with. Deliberately not the offer
/// itself: the core answers offers it parsed, so nothing the sender wrote can
/// be handed back to it as an address to dial.
Future<void> acceptFile({
  required BigInt id,
  required BigInt transferId,
  required String directory,
}) => RustLib.instance.api.crateApiClientAcceptFile(
  id: id,
  transferId: transferId,
  directory: directory,
);

/// Stop a running transfer, or decline an offer that never started.
///
/// Declining is silent: nothing was ever sent to whoever offered, which is
/// what "reported, never answered" buys.
Future<void> cancelTransfer({required BigInt id, required BigInt transferId}) =>
    RustLib.instance.api.crateApiClientCancelTransfer(
      id: id,
      transferId: transferId,
    );

/// Stop waiting out the reconnect backoff and try again now.
///
/// Does nothing unless the connection is actually waiting, so it is safe to
/// call from a button the user may press at the moment the connection returns
/// on its own. The connection, its id and its scrollback all survive — this
/// wakes the existing actor rather than replacing it.
Future<void> reconnect({required BigInt id}) =>
    RustLib.instance.api.crateApiClientReconnect(id: id);

/// Disconnect and release the connection.
///
/// Idempotent: disconnecting an unknown or already-closed connection succeeds,
/// so the UI does not have to track whether teardown already happened.
Future<void> disconnect({required BigInt id, String? reason}) =>
    RustLib.instance.api.crateApiClientDisconnect(id: id, reason: reason);

/// Remove everything an image carries beyond the picture.
///
/// EXIF, XMP, IPTC, text chunks, comments, embedded thumbnails and timestamps,
/// from JPEG, PNG, GIF and WebP. The container is rewritten and the image data
/// copied across untouched, so the pixels are byte-identical — nothing is lost
/// to a re-compress.
///
/// Not a `Result`: a file that is not an image is not a failure, only a file
/// nothing was removed from, and the caller may still want to send it. See
/// [`CleanOutcome`].
///
/// Synchronous, and on a worker thread rather than the UI isolate, because it
/// walks the whole file. A large photograph is a few milliseconds; a 128 MB
/// file is not, and blocking the interface for it would be visible.
Future<CleanOutcome> cleanMedia({required List<int> bytes}) =>
    RustLib.instance.api.crateApiClientCleanMedia(bytes: bytes);

/// The default port for IRC over TLS, so Dart does not hardcode it.
int defaultTlsPort() => RustLib.instance.api.crateApiClientDefaultTlsPort();

/// The port Tor's SOCKS listener uses, offered as the proxy form's default.
int torSocksPort() => RustLib.instance.api.crateApiClientTorSocksPort();
