// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `anchor_for`, `running`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Running`

/// Start it, and return where it is.
///
/// Starting one that is already running returns the one already there rather
/// than an error, so a settings screen rebuilt at the wrong moment cannot end
/// up with two.
///
/// `data_dir` must be the app's own private storage: the certificate authority
/// is written there and has to survive a restart, because the client's trust
/// anchor cannot be re-issued under it without every saved profile pointed at
/// the server breaking.
Future<LocalServerInfo> localServerStart({required String dataDir}) =>
    RustLib.instance.api.crateApiServerLocalServerStart(dataDir: dataDir);

/// Stop it. Idempotent, so a switch turned off twice is not an error.
///
/// Anyone connected is disconnected, which is the honest reading of switching
/// off a server: there is nothing left to be connected to.
Future<void> localServerStop() =>
    RustLib.instance.api.crateApiServerLocalServerStop();

/// Where it is, or null if it is not running.
///
/// For a screen coming back rather than one that just pressed the switch — the
/// answer has to survive the widget being rebuilt.
Future<LocalServerInfo?> localServerInfo() =>
    RustLib.instance.api.crateApiServerLocalServerInfo();

/// A running local server, as the settings screen sees it.
class LocalServerInfo {
  /// The loopback port it bound. `0` was asked for, so this is whatever the
  /// operating system had free.
  final int port;

  /// What it calls itself, which is what appears in its own messages.
  final String serverName;

  /// What it calls the network, which is what labels it in the rail.
  final String networkName;

  const LocalServerInfo({
    required this.port,
    required this.serverName,
    required this.networkName,
  });

  @override
  int get hashCode =>
      port.hashCode ^ serverName.hashCode ^ networkName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalServerInfo &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          serverName == other.serverName &&
          networkName == other.networkName;
}
