// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `rows`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Open, or create, the history database at `path`.
///
/// The path comes from Dart because only the app can say where its own data
/// directory is — every platform answers that differently, and two of them can
/// only be asked at runtime. Calling this again with a different path closes
/// the first, so there is never a write with two possible destinations.
Future<void> storeOpen({required String path}) =>
    RustLib.instance.api.crateApiStoreStoreOpen(path: path);

/// Stop keeping history. Idempotent, and never an error: turning off something
/// that is already off is what the user asked for either way.
Future<void> storeClose() => RustLib.instance.api.crateApiStoreStoreClose();

/// Whether history is currently being kept.
bool storeIsOpen() => RustLib.instance.api.crateApiStoreStoreIsOpen();

/// Write a batch of lines, and return the id each was stored under — `null`
/// for a line already stored, a replay of one the server sent before.
Future<List<PlatformInt64?>> storeAppend({required List<StoredLine> lines}) =>
    RustLib.instance.api.crateApiStoreStoreAppend(lines: lines);

/// The last `limit` lines of one conversation, oldest first.
Future<List<StoredLine>> storeRecent({
  required String profileId,
  required String conversation,
  required int limit,
}) => RustLib.instance.api.crateApiStoreStoreRecent(
  profileId: profileId,
  conversation: conversation,
  limit: limit,
);

/// The `limit` lines just older than the line at (`at_ms`, `id`), oldest
/// first: the next page up the scrollback.
Future<List<StoredLine>> storeBefore({
  required String profileId,
  required String conversation,
  required PlatformInt64 atMs,
  required PlatformInt64 id,
  required int limit,
}) => RustLib.instance.api.crateApiStoreStoreBefore(
  profileId: profileId,
  conversation: conversation,
  atMs: atMs,
  id: id,
  limit: limit,
);

/// The lines either side of one, for opening a conversation at it.
Future<List<StoredLine>> storeAround({
  required String profileId,
  required String conversation,
  required PlatformInt64 atMs,
  required PlatformInt64 id,
  required int radius,
}) => RustLib.instance.api.crateApiStoreStoreAround(
  profileId: profileId,
  conversation: conversation,
  atMs: atMs,
  id: id,
  radius: radius,
);

/// Lines matching what the user typed, newest first, optionally scoped to a
/// network and a conversation. `before_id` pages down from a previous result.
Future<List<StoredLine>> storeSearch({
  String? profileId,
  String? conversation,
  required String query,
  required int limit,
  PlatformInt64? beforeId,
}) => RustLib.instance.api.crateApiStoreStoreSearch(
  profileId: profileId,
  conversation: conversation,
  query: query,
  limit: limit,
  beforeId: beforeId,
);

/// How much history is being kept. The line count is approximate — see
/// `ddirc_core::store::approximate_count` — so the screen says "about".
Future<StoreStats> storeStats() =>
    RustLib.instance.api.crateApiStoreStoreStats();

/// Delete every stored line, and give the disk space back.
Future<void> storeClear() => RustLib.instance.api.crateApiStoreStoreClear();

/// Delete one conversation's history, leaving the rest.
Future<void> storeForget({
  required String profileId,
  required String conversation,
}) => RustLib.instance.api.crateApiStoreStoreForget(
  profileId: profileId,
  conversation: conversation,
);

/// Delete everything kept for one saved network, for when it is deleted.
Future<void> storeForgetProfile({required String profileId}) =>
    RustLib.instance.api.crateApiStoreStoreForgetProfile(profileId: profileId);

/// Every conversation's state, on every network.
Future<List<ConversationState>> storeConversationStates() =>
    RustLib.instance.api.crateApiStoreStoreConversationStates();

/// Write one conversation's state; one with nothing left in it loses its row.
Future<void> storeSetConversationState({required ConversationState state}) =>
    RustLib.instance.api.crateApiStoreStoreSetConversationState(state: state);

/// Pins and saved messages: of one kind or all, on one network or all, in
/// one conversation or all. Oldest message first.
Future<List<Mark>> storeMarks({
  PlatformInt64? kind,
  String? profileId,
  String? conversation,
}) => RustLib.instance.api.crateApiStoreStoreMarks(
  kind: kind,
  profileId: profileId,
  conversation: conversation,
);

/// Pin or save a message, returning the mark's id. Marking the same message
/// twice returns the first mark's id rather than making a second.
Future<PlatformInt64> storeAddMark({required Mark mark}) =>
    RustLib.instance.api.crateApiStoreStoreAddMark(mark: mark);

/// Unpin or unsave.
Future<void> storeRemoveMark({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiStoreStoreRemoveMark(id: id);

/// Everyone the user has annotated, on every network.
Future<List<Person>> storePeople() =>
    RustLib.instance.api.crateApiStoreStorePeople();

/// Write what is known about one person, replacing what was there. A person
/// with every field cleared loses their row.
Future<void> storeSetPerson({required Person person}) =>
    RustLib.instance.api.crateApiStoreStoreSetPerson(person: person);

/// Forget everyone on one network — for when the network itself is forgotten.
Future<void> storeForgetPeople({required String profileId}) =>
    RustLib.instance.api.crateApiStoreStoreForgetPeople(profileId: profileId);

/// Every identity the user has made.
Future<List<Persona>> storePersonas() =>
    RustLib.instance.api.crateApiStoreStorePersonas();

/// Create or rename an identity.
Future<void> storeSetPersona({required Persona persona}) =>
    RustLib.instance.api.crateApiStoreStoreSetPersona(persona: persona);

/// Forget an identity, and every remembered nick that was hers.
Future<void> storeForgetPersona({required String id}) =>
    RustLib.instance.api.crateApiStoreStoreForgetPersona(id: id);

/// Every remembered (persona, network) → nick, for the app to hold in memory.
Future<List<PersonaNick>> storePersonaNicks() =>
    RustLib.instance.api.crateApiStoreStorePersonaNicks();

/// Remember the nick a persona wears on a network, replacing any earlier one.
Future<void> storeSetPersonaNick({required PersonaNick nick}) =>
    RustLib.instance.api.crateApiStoreStoreSetPersonaNick(nick: nick);

/// Forget every persona's nick on one network — for when the network itself
/// is forgotten, alongside [`store_forget_people`].
Future<void> storeForgetPersonaNicks({required String networkId}) => RustLib
    .instance
    .api
    .crateApiStoreStoreForgetPersonaNicks(networkId: networkId);

/// What the user keeps about one conversation apart from its messages: an
/// unsent draft, how far it was read, whether it is pinned or archived.
class ConversationState {
  final String profileId;

  /// Already case-folded by the caller.
  final String conversation;
  final String? draft;
  final String? draftReplyMsgid;
  final PlatformInt64? readLineId;
  final PlatformInt64? readAtMs;

  /// Place among the pinned conversations, lowest first; null when not
  /// pinned.
  final PlatformInt64? pinOrder;
  final bool archived;

  const ConversationState({
    required this.profileId,
    required this.conversation,
    this.draft,
    this.draftReplyMsgid,
    this.readLineId,
    this.readAtMs,
    this.pinOrder,
    required this.archived,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      conversation.hashCode ^
      draft.hashCode ^
      draftReplyMsgid.hashCode ^
      readLineId.hashCode ^
      readAtMs.hashCode ^
      pinOrder.hashCode ^
      archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationState &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          conversation == other.conversation &&
          draft == other.draft &&
          draftReplyMsgid == other.draftReplyMsgid &&
          readLineId == other.readLineId &&
          readAtMs == other.readAtMs &&
          pinOrder == other.pinOrder &&
          archived == other.archived;
}

/// A message the user pinned (`kind` 1) or saved (`kind` 2): a copy of it,
/// so it outlives the line it came from.
class Mark {
  /// Zero when adding.
  final PlatformInt64 id;
  final PlatformInt64 kind;
  final String profileId;
  final String conversation;
  final PlatformInt64? lineId;
  final String? msgid;
  final PlatformInt64 atMs;
  final String? sender;
  final List<TextSpan> spans;
  final PlatformInt64 createdMs;

  const Mark({
    required this.id,
    required this.kind,
    required this.profileId,
    required this.conversation,
    this.lineId,
    this.msgid,
    required this.atMs,
    this.sender,
    required this.spans,
    required this.createdMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      profileId.hashCode ^
      conversation.hashCode ^
      lineId.hashCode ^
      msgid.hashCode ^
      atMs.hashCode ^
      sender.hashCode ^
      spans.hashCode ^
      createdMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mark &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          profileId == other.profileId &&
          conversation == other.conversation &&
          lineId == other.lineId &&
          msgid == other.msgid &&
          atMs == other.atMs &&
          sender == other.sender &&
          spans == other.spans &&
          createdMs == other.createdMs;
}

/// What the user has written down about one person on one network: a name
/// to show instead of the nick, a note, a colour, a picture.
///
/// The user's annotation, never anything the person sent. Kept in the same
/// database as history and behind the same switch, because it is still a
/// record of who they talk to. `nick` is folded to lower case by the caller.
class Person {
  final String profileId;
  final String nick;
  final String? alias;
  final String? note;

  /// ARGB, as `Color.value` on the Dart side.
  final PlatformInt64? color;

  /// A small PNG, downscaled before it gets here.
  final Uint8List? avatar;

  /// Seed for a generated pixel avatar, when no picture was chosen.
  final PlatformInt64? pixelSeed;

  const Person({
    required this.profileId,
    required this.nick,
    this.alias,
    this.note,
    this.color,
    this.avatar,
    this.pixelSeed,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      nick.hashCode ^
      alias.hashCode ^
      note.hashCode ^
      color.hashCode ^
      avatar.hashCode ^
      pixelSeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Person &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          nick == other.nick &&
          alias == other.alias &&
          note == other.note &&
          color == other.color &&
          avatar == other.avatar &&
          pixelSeed == other.pixelSeed;
}

/// One of the user's own identities: a private label a network never sees.
///
/// The nick a persona actually connects under is per network and lives in
/// [`PersonaNick`], because one identity wears a different, unlinkable handle
/// on each server it touches.
class Persona {
  final String id;
  final String label;

  const Persona({required this.id, required this.label});

  @override
  int get hashCode => id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Persona &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label;
}

/// The nick one persona wears on one saved network, generated once and kept.
class PersonaNick {
  final String personaId;
  final String networkId;
  final String nick;

  const PersonaNick({
    required this.personaId,
    required this.networkId,
    required this.nick,
  });

  @override
  int get hashCode => personaId.hashCode ^ networkId.hashCode ^ nick.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaNick &&
          runtimeType == other.runtimeType &&
          personaId == other.personaId &&
          networkId == other.networkId &&
          nick == other.nick;
}

/// What the store currently holds, for the settings screen to report.
class StoreStats {
  final PlatformInt64 lines;
  final PlatformInt64 bytes;

  const StoreStats({required this.lines, required this.bytes});

  @override
  int get hashCode => lines.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreStats &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          bytes == other.bytes;
}

/// One stored line, on its way in or out.
///
/// `kind` is an opaque small integer belonging to the app: zero for a message,
/// and for a system line whatever category the UI files it under. The core
/// deliberately does not know what those mean — a UI category should never
/// become a database migration.
class StoredLine {
  /// The id the store gave this line, on the way out; ignored on the way in.
  ///
  /// What a read position, a pin or a search result holds on to — a server
  /// id is only there when the server sent one.
  final PlatformInt64? id;

  /// Which saved network this belongs to.
  final String profileId;

  /// The conversation's key, already case-folded by the caller. IRC's case
  /// mapping is a property of the server, so the app owns that rule.
  final String conversation;

  /// Milliseconds since the Unix epoch.
  final PlatformInt64 atMs;

  /// Who said it, or null for a system line.
  final String? sender;

  /// Their channel privilege at the time, e.g. `@`.
  final String? senderPrefix;

  /// The line itself, styled. Stored as codes and re-parsed on the way back,
  /// so restored history renders exactly as it did live.
  final List<TextSpan> spans;
  final bool isSelf;
  final bool isMention;
  final bool isAction;
  final bool isNotice;

  /// What kind of system line this is. Meaningless when `sender` is set.
  final PlatformInt64 kind;

  /// The server's id for the line, when it had one.
  final String? msgid;

  /// What the line replies to, if it is a reply.
  final ReplyRef? replyTo;

  const StoredLine({
    this.id,
    required this.profileId,
    required this.conversation,
    required this.atMs,
    this.sender,
    this.senderPrefix,
    required this.spans,
    required this.isSelf,
    required this.isMention,
    required this.isAction,
    required this.isNotice,
    required this.kind,
    this.msgid,
    this.replyTo,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      profileId.hashCode ^
      conversation.hashCode ^
      atMs.hashCode ^
      sender.hashCode ^
      senderPrefix.hashCode ^
      spans.hashCode ^
      isSelf.hashCode ^
      isMention.hashCode ^
      isAction.hashCode ^
      isNotice.hashCode ^
      kind.hashCode ^
      msgid.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredLine &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          profileId == other.profileId &&
          conversation == other.conversation &&
          atMs == other.atMs &&
          sender == other.sender &&
          senderPrefix == other.senderPrefix &&
          spans == other.spans &&
          isSelf == other.isSelf &&
          isMention == other.isMention &&
          isAction == other.isAction &&
          isNotice == other.isNotice &&
          kind == other.kind &&
          msgid == other.msgid &&
          replyTo == other.replyTo;
}
