// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// Open, or create, the history database at `path`.
///
/// The path comes from Dart because only the app can say where its own data
/// directory is — every platform answers that differently, and two of them can
/// only be asked at runtime. Calling this again with a different path closes
/// the first, so there is never a write with two possible destinations.
Future<void> storeOpen({required String path}) =>
    RustLib.instance.api.crateApiStoreStoreOpen(path: path);

/// Stop keeping history. Idempotent, and never an error: turning off something
/// that is already off is what the user asked for either way.
Future<void> storeClose() => RustLib.instance.api.crateApiStoreStoreClose();

/// Whether history is currently being kept.
bool storeIsOpen() => RustLib.instance.api.crateApiStoreStoreIsOpen();

/// Write a batch of lines.
Future<void> storeAppend({required List<StoredLine> lines}) =>
    RustLib.instance.api.crateApiStoreStoreAppend(lines: lines);

/// The last `limit` lines of one conversation, oldest first.
Future<List<StoredLine>> storeRecent({
  required String profileId,
  required String conversation,
  required int limit,
}) => RustLib.instance.api.crateApiStoreStoreRecent(
  profileId: profileId,
  conversation: conversation,
  limit: limit,
);

/// How much history is being kept.
Future<StoreStats> storeStats() =>
    RustLib.instance.api.crateApiStoreStoreStats();

/// Delete every stored line, and give the disk space back.
Future<void> storeClear() => RustLib.instance.api.crateApiStoreStoreClear();

/// Delete one conversation's history, leaving the rest.
Future<void> storeForget({
  required String profileId,
  required String conversation,
}) => RustLib.instance.api.crateApiStoreStoreForget(
  profileId: profileId,
  conversation: conversation,
);

/// What the store currently holds, for the settings screen to report.
class StoreStats {
  final PlatformInt64 lines;
  final PlatformInt64 bytes;

  const StoreStats({required this.lines, required this.bytes});

  @override
  int get hashCode => lines.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreStats &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          bytes == other.bytes;
}

/// One stored line, on its way in or out.
///
/// `kind` is an opaque small integer belonging to the app: zero for a message,
/// and for a system line whatever category the UI files it under. The core
/// deliberately does not know what those mean — a UI category should never
/// become a database migration.
class StoredLine {
  /// Which saved network this belongs to.
  final String profileId;

  /// The conversation's key, already case-folded by the caller. IRC's case
  /// mapping is a property of the server, so the app owns that rule.
  final String conversation;

  /// Milliseconds since the Unix epoch.
  final PlatformInt64 atMs;

  /// Who said it, or null for a system line.
  final String? sender;

  /// Their channel privilege at the time, e.g. `@`.
  final String? senderPrefix;

  /// The line itself, styled. Stored as codes and re-parsed on the way back,
  /// so restored history renders exactly as it did live.
  final List<TextSpan> spans;
  final bool isSelf;
  final bool isMention;
  final bool isAction;
  final bool isNotice;

  /// What kind of system line this is. Meaningless when `sender` is set.
  final PlatformInt64 kind;

  const StoredLine({
    required this.profileId,
    required this.conversation,
    required this.atMs,
    this.sender,
    this.senderPrefix,
    required this.spans,
    required this.isSelf,
    required this.isMention,
    required this.isAction,
    required this.isNotice,
    required this.kind,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      conversation.hashCode ^
      atMs.hashCode ^
      sender.hashCode ^
      senderPrefix.hashCode ^
      spans.hashCode ^
      isSelf.hashCode ^
      isMention.hashCode ^
      isAction.hashCode ^
      isNotice.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredLine &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          conversation == other.conversation &&
          atMs == other.atMs &&
          sender == other.sender &&
          senderPrefix == other.senderPrefix &&
          spans == other.spans &&
          isSelf == other.isSelf &&
          isMention == other.isMention &&
          isAction == other.isAction &&
          isNotice == other.isNotice &&
          kind == other.kind;
}
