// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Open, or create, the history database at `path`.
///
/// The path comes from Dart because only the app can say where its own data
/// directory is — every platform answers that differently, and two of them can
/// only be asked at runtime. Calling this again with a different path closes
/// the first, so there is never a write with two possible destinations.
Future<void> storeOpen({required String path}) =>
    RustLib.instance.api.crateApiStoreStoreOpen(path: path);

/// Stop keeping history. Idempotent, and never an error: turning off something
/// that is already off is what the user asked for either way.
Future<void> storeClose() => RustLib.instance.api.crateApiStoreStoreClose();

/// Whether history is currently being kept.
bool storeIsOpen() => RustLib.instance.api.crateApiStoreStoreIsOpen();

/// Write a batch of lines.
Future<void> storeAppend({required List<StoredLine> lines}) =>
    RustLib.instance.api.crateApiStoreStoreAppend(lines: lines);

/// The last `limit` lines of one conversation, oldest first.
Future<List<StoredLine>> storeRecent({
  required String profileId,
  required String conversation,
  required int limit,
}) => RustLib.instance.api.crateApiStoreStoreRecent(
  profileId: profileId,
  conversation: conversation,
  limit: limit,
);

/// How much history is being kept.
Future<StoreStats> storeStats() =>
    RustLib.instance.api.crateApiStoreStoreStats();

/// Delete every stored line, and give the disk space back.
Future<void> storeClear() => RustLib.instance.api.crateApiStoreStoreClear();

/// Delete one conversation's history, leaving the rest.
Future<void> storeForget({
  required String profileId,
  required String conversation,
}) => RustLib.instance.api.crateApiStoreStoreForget(
  profileId: profileId,
  conversation: conversation,
);

/// Everyone the user has annotated, on every network.
Future<List<Person>> storePeople() =>
    RustLib.instance.api.crateApiStoreStorePeople();

/// Write what is known about one person, replacing what was there. A person
/// with every field cleared loses their row.
Future<void> storeSetPerson({required Person person}) =>
    RustLib.instance.api.crateApiStoreStoreSetPerson(person: person);

/// Forget everyone on one network — for when the network itself is forgotten.
Future<void> storeForgetPeople({required String profileId}) =>
    RustLib.instance.api.crateApiStoreStoreForgetPeople(profileId: profileId);

/// Every identity the user has made.
Future<List<Persona>> storePersonas() =>
    RustLib.instance.api.crateApiStoreStorePersonas();

/// Create or rename an identity.
Future<void> storeSetPersona({required Persona persona}) =>
    RustLib.instance.api.crateApiStoreStoreSetPersona(persona: persona);

/// Forget an identity, and every remembered nick that was hers.
Future<void> storeForgetPersona({required String id}) =>
    RustLib.instance.api.crateApiStoreStoreForgetPersona(id: id);

/// Every remembered (persona, network) → nick, for the app to hold in memory.
Future<List<PersonaNick>> storePersonaNicks() =>
    RustLib.instance.api.crateApiStoreStorePersonaNicks();

/// Remember the nick a persona wears on a network, replacing any earlier one.
Future<void> storeSetPersonaNick({required PersonaNick nick}) =>
    RustLib.instance.api.crateApiStoreStoreSetPersonaNick(nick: nick);

/// Forget every persona's nick on one network — for when the network itself
/// is forgotten, alongside [`store_forget_people`].
Future<void> storeForgetPersonaNicks({required String networkId}) => RustLib
    .instance
    .api
    .crateApiStoreStoreForgetPersonaNicks(networkId: networkId);

/// What the user has written down about one person on one network: a name
/// to show instead of the nick, a note, a colour, a picture.
///
/// The user's annotation, never anything the person sent. Kept in the same
/// database as history and behind the same switch, because it is still a
/// record of who they talk to. `nick` is folded to lower case by the caller.
class Person {
  final String profileId;
  final String nick;
  final String? alias;
  final String? note;

  /// ARGB, as `Color.value` on the Dart side.
  final PlatformInt64? color;

  /// A small PNG, downscaled before it gets here.
  final Uint8List? avatar;

  /// Seed for a generated pixel avatar, when no picture was chosen.
  final PlatformInt64? pixelSeed;

  const Person({
    required this.profileId,
    required this.nick,
    this.alias,
    this.note,
    this.color,
    this.avatar,
    this.pixelSeed,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      nick.hashCode ^
      alias.hashCode ^
      note.hashCode ^
      color.hashCode ^
      avatar.hashCode ^
      pixelSeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Person &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          nick == other.nick &&
          alias == other.alias &&
          note == other.note &&
          color == other.color &&
          avatar == other.avatar &&
          pixelSeed == other.pixelSeed;
}

/// One of the user's own identities: a private label a network never sees.
///
/// The nick a persona actually connects under is per network and lives in
/// [`PersonaNick`], because one identity wears a different, unlinkable handle
/// on each server it touches.
class Persona {
  final String id;
  final String label;

  const Persona({required this.id, required this.label});

  @override
  int get hashCode => id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Persona &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label;
}

/// The nick one persona wears on one saved network, generated once and kept.
class PersonaNick {
  final String personaId;
  final String networkId;
  final String nick;

  const PersonaNick({
    required this.personaId,
    required this.networkId,
    required this.nick,
  });

  @override
  int get hashCode => personaId.hashCode ^ networkId.hashCode ^ nick.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonaNick &&
          runtimeType == other.runtimeType &&
          personaId == other.personaId &&
          networkId == other.networkId &&
          nick == other.nick;
}

/// What the store currently holds, for the settings screen to report.
class StoreStats {
  final PlatformInt64 lines;
  final PlatformInt64 bytes;

  const StoreStats({required this.lines, required this.bytes});

  @override
  int get hashCode => lines.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreStats &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          bytes == other.bytes;
}

/// One stored line, on its way in or out.
///
/// `kind` is an opaque small integer belonging to the app: zero for a message,
/// and for a system line whatever category the UI files it under. The core
/// deliberately does not know what those mean — a UI category should never
/// become a database migration.
class StoredLine {
  /// Which saved network this belongs to.
  final String profileId;

  /// The conversation's key, already case-folded by the caller. IRC's case
  /// mapping is a property of the server, so the app owns that rule.
  final String conversation;

  /// Milliseconds since the Unix epoch.
  final PlatformInt64 atMs;

  /// Who said it, or null for a system line.
  final String? sender;

  /// Their channel privilege at the time, e.g. `@`.
  final String? senderPrefix;

  /// The line itself, styled. Stored as codes and re-parsed on the way back,
  /// so restored history renders exactly as it did live.
  final List<TextSpan> spans;
  final bool isSelf;
  final bool isMention;
  final bool isAction;
  final bool isNotice;

  /// What kind of system line this is. Meaningless when `sender` is set.
  final PlatformInt64 kind;

  /// The server's id for the line, when it had one.
  final String? msgid;

  /// What the line replies to, if it is a reply.
  final ReplyRef? replyTo;

  const StoredLine({
    required this.profileId,
    required this.conversation,
    required this.atMs,
    this.sender,
    this.senderPrefix,
    required this.spans,
    required this.isSelf,
    required this.isMention,
    required this.isAction,
    required this.isNotice,
    required this.kind,
    this.msgid,
    this.replyTo,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      conversation.hashCode ^
      atMs.hashCode ^
      sender.hashCode ^
      senderPrefix.hashCode ^
      spans.hashCode ^
      isSelf.hashCode ^
      isMention.hashCode ^
      isAction.hashCode ^
      isNotice.hashCode ^
      kind.hashCode ^
      msgid.hashCode ^
      replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredLine &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          conversation == other.conversation &&
          atMs == other.atMs &&
          sender == other.sender &&
          senderPrefix == other.senderPrefix &&
          spans == other.spans &&
          isSelf == other.isSelf &&
          isMention == other.isMention &&
          isAction == other.isAction &&
          isNotice == other.isNotice &&
          kind == other.kind &&
          msgid == other.msgid &&
          replyTo == other.replyTo;
}
