// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `service`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Start the bundled Tor and return the loopback port it answers SOCKS5 on.
///
/// Returns as soon as there is a port, which is well before Tor can carry
/// anything: bootstrapping needs a directory consensus off the network, and
/// how long that takes depends on the network. Follow [`tor_status_stream`]
/// for the rest.
///
/// Starting when it is already running returns the port it is already on
/// rather than an error, so a settings screen rebuilt at the wrong moment
/// cannot end up with two.
///
/// `data_dir` is where Tor keeps its state and its directory cache. It must be
/// the app's own private storage: the cache is not secret, but the guard list
/// is a record of how this machine reaches the network.
Future<int> torStart({required String dataDir}) =>
    RustLib.instance.api.crateApiTorTorStart(dataDir: dataDir);

/// Stop it. Idempotent, so a switch turned off twice is not an error.
///
/// Connections currently routed through it are cut. That is deliberate: after
/// turning Tor off, nothing should still be connected by way of it, and
/// nothing should quietly fall back to a direct route it was never given
/// permission to take.
Future<void> torStop() => RustLib.instance.api.crateApiTorTorStop();

/// The port Tor is on, or null if it is not running.
///
/// For a UI coming back to a screen rather than one that just pressed the
/// switch — the answer has to survive the widget being rebuilt.
Future<int?> torPort() => RustLib.instance.api.crateApiTorTorPort();

/// Follow the bootstrap. In Dart this is a `Stream`.
///
/// The current status is delivered first, so a screen that subscribes late
/// still knows where things stand rather than waiting for the next change.
/// The stream ends when Tor stops.
Stream<TorStatus> torStatusStream() =>
    RustLib.instance.api.crateApiTorTorStatusStream();

/// How far along Tor is, for the settings screen.
class TorStatus {
  /// Connections through the proxy will now succeed. Before this they
  /// *wait*, rather than failing — so a network dialled early connects late
  /// rather than erroring.
  final bool ready;

  /// 0.0 to 1.0.
  final double progress;

  /// One line, in Arti's words.
  final String summary;

  /// Why it is stuck, when Arti knows — a censored network, no route out, a
  /// clock too far off for anything to verify. The only part of this the
  /// user can act on, so it is the part shown in full.
  final String? blocked;

  const TorStatus({
    required this.ready,
    required this.progress,
    required this.summary,
    this.blocked,
  });

  @override
  int get hashCode =>
      ready.hashCode ^ progress.hashCode ^ summary.hashCode ^ blocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorStatus &&
          runtimeType == other.runtimeType &&
          ready == other.ready &&
          progress == other.progress &&
          summary == other.summary &&
          blocked == other.blocked;
}
