// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class AuthOutcome with _$AuthOutcome {
  const AuthOutcome._();

  /// Authenticated before joining anything.
  const factory AuthOutcome.sasl() = AuthOutcome_Sasl;

  /// Weaker: authenticated after connecting, so we were briefly present
  /// unauthenticated. Worth surfacing to the user.
  const factory AuthOutcome.nickServFallback({required String reason}) =
      AuthOutcome_NickServFallback;
  const factory AuthOutcome.anonymous() = AuthOutcome_Anonymous;
}

/// A chat message, already sanitised.
class ChatMessage {
  final Target target;
  final String sender;
  final String? senderPrefix;
  final List<TextSpan> spans;

  /// True if we sent it, so the UI can align it opposite.
  final bool isSelf;

  /// True if our nick was mentioned, for the highlight tint.
  final bool isMention;
  final bool isAction;
  final bool isNotice;

  const ChatMessage({
    required this.target,
    required this.sender,
    this.senderPrefix,
    required this.spans,
    required this.isSelf,
    required this.isMention,
    required this.isAction,
    required this.isNotice,
  });

  @override
  int get hashCode =>
      target.hashCode ^
      sender.hashCode ^
      senderPrefix.hashCode ^
      spans.hashCode ^
      isSelf.hashCode ^
      isMention.hashCode ^
      isAction.hashCode ^
      isNotice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          sender == other.sender &&
          senderPrefix == other.senderPrefix &&
          spans == other.spans &&
          isSelf == other.isSelf &&
          isMention == other.isMention &&
          isAction == other.isAction &&
          isNotice == other.isNotice;
}

@freezed
sealed class CleanOutcome with _$CleanOutcome {
  const CleanOutcome._();

  /// Metadata was found and removed. `bytes` is the file to send.
  const factory CleanOutcome.cleaned({
    required Uint8List bytes,

    /// `"JPEG"`, `"PNG"`, `"GIF"` or `"WebP"`.
    required String kind,
    required List<RemovedItem> removed,
  }) = CleanOutcome_Cleaned;

  /// A supported image that had nothing to remove — a screenshot, usually.
  ///
  /// Deliberately not `Cleaned` with an empty list: the honest thing to tell
  /// someone is "there was nothing in it", not "it has been cleaned", which
  /// sounds like work was done and invites trust in the wrong place. The
  /// original bytes are unchanged, so none are sent back across the bridge.
  const factory CleanOutcome.alreadyClean({required String kind}) =
      CleanOutcome_AlreadyClean;

  /// Not an image this can rewrite. Not an error: the caller may still want
  /// to send it, and now knows it was not cleaned.
  const factory CleanOutcome.notAnImage() = CleanOutcome_NotAnImage;

  /// A supported format that did not parse. Worth separating from
  /// `NotAnImage`, because this one probably means a damaged file.
  const factory CleanOutcome.malformed({required String detail}) =
      CleanOutcome_Malformed;
}

@freezed
sealed class ConnectionStatus with _$ConnectionStatus {
  const ConnectionStatus._();

  const factory ConnectionStatus.disconnected() = ConnectionStatus_Disconnected;
  const factory ConnectionStatus.connecting() = ConnectionStatus_Connecting;
  const factory ConnectionStatus.registering() = ConnectionStatus_Registering;
  const factory ConnectionStatus.connected() = ConnectionStatus_Connected;
  const factory ConnectionStatus.reconnecting({
    required BigInt retryInSecs,
    required int attempt,
  }) = ConnectionStatus_Reconnecting;
}

@freezed
sealed class IrcEvent with _$IrcEvent {
  const IrcEvent._();

  const factory IrcEvent.status({
    required ConnectionStatus status,
    String? detail,
  }) = IrcEvent_Status;
  const factory IrcEvent.registered({
    required String nick,
    String? network,
    required AuthOutcome auth,
  }) = IrcEvent_Registered;
  const factory IrcEvent.networkNamed({required String network}) =
      IrcEvent_NetworkNamed;
  const factory IrcEvent.message({required ChatMessage message}) =
      IrcEvent_Message;
  const factory IrcEvent.joined({
    required String channel,
    required String nick,
    required bool isSelf,
  }) = IrcEvent_Joined;
  const factory IrcEvent.parted({
    required String channel,
    required String nick,
    required bool isSelf,
    String? reason,
  }) = IrcEvent_Parted;
  const factory IrcEvent.quit({
    required String channel,
    required String nick,
    String? reason,
  }) = IrcEvent_Quit;
  const factory IrcEvent.nickChanged({
    required String channel,
    required String old,
    required String new_,
    required bool isSelf,
  }) = IrcEvent_NickChanged;
  const factory IrcEvent.topicChanged({
    required String channel,
    required String topic,
    String? setBy,
  }) = IrcEvent_TopicChanged;
  const factory IrcEvent.memberList({
    required String channel,
    required List<MemberView> members,
  }) = IrcEvent_MemberList;
  const factory IrcEvent.modeChanged({
    required String channel,
    String? by,
    required List<String> affected,
  }) = IrcEvent_ModeChanged;

  /// Messages discarded by flood protection or UI backpressure. Surfaced so a
  /// gap in a conversation is never silently mistaken for silence.
  const factory IrcEvent.messagesDropped({
    String? channel,
    required BigInt count,
  }) = IrcEvent_MessagesDropped;
  const factory IrcEvent.error({required String message, required bool fatal}) =
      IrcEvent_Error;
}

/// A channel member.
class MemberView {
  final String nick;

  /// Highest-privilege prefix, e.g. `@` or `+`.
  final String? prefix;
  final bool away;

  const MemberView({required this.nick, this.prefix, required this.away});

  @override
  int get hashCode => nick.hashCode ^ prefix.hashCode ^ away.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberView &&
          runtimeType == other.runtimeType &&
          nick == other.nick &&
          prefix == other.prefix &&
          away == other.away;
}

/// A SOCKS5 proxy to dial through.
///
/// SOCKS5 only, which is what the transport supports and also what Tor's local
/// listener speaks. The tunnel carries the connection; TLS is still negotiated
/// end to end with the IRC server through it, so the proxy sees ciphertext to a
/// host it was told about and nothing more.
///
/// Dart resolves the app-wide setting against any per-server override before
/// building this, so `ServerConfig::proxy` is an answer rather than a policy.
class ProxyConfig {
  final String host;
  final int port;

  /// SOCKS5 username/password auth (RFC 1929). Both or neither.
  ///
  /// Sent to the proxy in the clear, before any TLS exists — it proves who
  /// you are to the proxy and protects nothing else.
  final String? username;
  final String? password;

  const ProxyConfig({
    required this.host,
    required this.port,
    this.username,
    this.password,
  });

  @override
  int get hashCode =>
      host.hashCode ^ port.hashCode ^ username.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password;
}

/// One thing taken out of a file.
class RemovedItem {
  /// What it was: `"EXIF"`, `"XMP"`, `"comment"`, and so on.
  final String what;
  final BigInt bytes;

  const RemovedItem({required this.what, required this.bytes});

  @override
  int get hashCode => what.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemovedItem &&
          runtimeType == other.runtimeType &&
          what == other.what &&
          bytes == other.bytes;
}

/// How to reach a server.
///
/// TLS is not configurable — every connection uses it. Passwords arrive as
/// plain strings from Dart and are moved into zeroizing storage on the Rust
/// side immediately.
class ServerConfig {
  final String host;
  final int port;
  final String nickname;
  final List<String> altNicks;
  final String? username;
  final String? realname;
  final List<String> channels;
  final String? saslAccount;
  final String? saslPassword;
  final String? nickservPassword;
  final String? serverPassword;

  /// Dial through this proxy rather than connecting directly. There is no
  /// fallback: if it is set and unreachable, the connection fails.
  final ProxyConfig? proxy;

  const ServerConfig({
    required this.host,
    required this.port,
    required this.nickname,
    required this.altNicks,
    this.username,
    this.realname,
    required this.channels,
    this.saslAccount,
    this.saslPassword,
    this.nickservPassword,
    this.serverPassword,
    this.proxy,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      nickname.hashCode ^
      altNicks.hashCode ^
      username.hashCode ^
      realname.hashCode ^
      channels.hashCode ^
      saslAccount.hashCode ^
      saslPassword.hashCode ^
      nickservPassword.hashCode ^
      serverPassword.hashCode ^
      proxy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          nickname == other.nickname &&
          altNicks == other.altNicks &&
          username == other.username &&
          realname == other.realname &&
          channels == other.channels &&
          saslAccount == other.saslAccount &&
          saslPassword == other.saslPassword &&
          nickservPassword == other.nickservPassword &&
          serverPassword == other.serverPassword &&
          proxy == other.proxy;
}

/// Styling for a run of message text.
class SpanStyle {
  final bool bold;
  final bool italic;
  final bool underline;
  final bool strikethrough;
  final bool monospace;
  final bool inverse;

  /// mIRC colour index, if any.
  final int? fg;
  final int? bg;

  const SpanStyle({
    required this.bold,
    required this.italic,
    required this.underline,
    required this.strikethrough,
    required this.monospace,
    required this.inverse,
    this.fg,
    this.bg,
  });

  @override
  int get hashCode =>
      bold.hashCode ^
      italic.hashCode ^
      underline.hashCode ^
      strikethrough.hashCode ^
      monospace.hashCode ^
      inverse.hashCode ^
      fg.hashCode ^
      bg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpanStyle &&
          runtimeType == other.runtimeType &&
          bold == other.bold &&
          italic == other.italic &&
          underline == other.underline &&
          strikethrough == other.strikethrough &&
          monospace == other.monospace &&
          inverse == other.inverse &&
          fg == other.fg &&
          bg == other.bg;
}

@freezed
sealed class Target with _$Target {
  const Target._();

  const factory Target.channel({required String name}) = Target_Channel;
  const factory Target.direct({required String nick}) = Target_Direct;
}

/// A run of message text sharing one style.
///
/// The text is guaranteed free of control characters: the core strips them
/// before this type is ever built.
class TextSpan {
  final String text;
  final SpanStyle style;

  const TextSpan({required this.text, required this.style});

  @override
  int get hashCode => text.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextSpan &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          style == other.style;
}
